### ISSUE TITLE
[Bug]: Monsters in AV Premium Module missing Tag

### ISSUE THREAD

**Issue by mikkynezumi** [foundryvtt/foundryvtt-premium-content#116]
### What happened?

Monsters in AV are missing their primary trait (Ex. Fey, Aberration)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

4.0.3

**Comment by JamzTheMan** [comment]
I did some testing after noticing this as well yesterday.

If you re-import the adventure on v10, you loose most of the tags for imported actors and actors on the scenes. Compendium versions seem to be ok still.

IF you delete ALL AV content (scenes, actors, journels, playlists, macros, etc) and re-import, it then seems to work ok.

*I forgot to delete macros once and it imported broken actors without tags, so it seems all content needs to be deleted, not just the actors/scenes)*

**Comment by silvative** [comment]
I am unable to reproduce the issue on a fresh import in a newly created world with version 1.2.0 of the module and build 288 of V10 Foundry.

![image](https://user-images.githubusercontent.com/66365038/200057150-c798b400-dcc2-4ec4-8784-7fe0cd16c12a.png)
