### ISSUE TITLE
Missing Macro in Abomination Vaults

### ISSUE THREAD

**Issue by Sparkasaurusmex** [foundryvtt/foundryvtt-premium-content#117]
### What happened?

Journal Entry for A07 links to a macro for Stonescale Spirits, but the macro does not exist.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.2.0

**Comment by MrChessur** [comment]
Second this Issue

**Comment by JamzTheMan** [comment]
Came to report the same. :) Fresh install, no modules.

**Comment by jhubsharp** [comment]
Still an issue after the recent fix

**Comment by silvative** [comment]
Good catch, the macro had accidentally been excluded from the adventure pack so it wasn't being sent out to users!

**Comment by Taurahh** [comment]
This macro is still missing from a fresh 2.0 import.
