### ISSUE TITLE
[Feature]: Change macro variable names to harden against potential conflicts

### ISSUE THREAD

**Issue by MrChessur** [foundryvtt/foundryvtt-premium-content#120]
### What happened?

Foundry v10 Build 286
Pf2e 4.1.2
Abomination Vaults 1.2.0

Macros like Flickerwisp Reveal and Skeletal Giant do not execute properly because of a change in Pf2e data. Ones with tiles have a deprecation warning. These are with no other modules activated, just pf2e Abomination Vaults.

![image](https://user-images.githubusercontent.com/28309284/191753843-42a739f0-58b6-487e-bd9c-94885cdc2eae.png)
![image](https://user-images.githubusercontent.com/28309284/191754208-9f3f13c6-bef6-46c3-bc06-11b0a81f0217.png)

Changing the declared const also causes an error mentioning token.update is no longer supported. The weirdest part is the fact that you can get the macros to work if you install Advanced Macros and have it activated when executing the macro.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.2.0

**Comment by drewg13** [comment]
Renaming every occurrence of `token` to something else, like `token1`, fixes this, as an expedient solution.  Foundry doesn't seem to like using `token` as a variable name in a macro, although it works just fine in the console.  This appears to be true in other systems as well, so this is likely a core issue.

Looks like it's related to this bit of code, so using `speaker`, `actor`, `token`, or `character` as variable names in macros is not going to work for now.

```js
/**
   * Execute the command as a script macro.
   * Script Macros are wrapped in an async IIFE to allow the use of asynchronous commands and await statements.
   * @param {object} [options={}]
   * @param {Actor} [options.actor]
   * @param {Token} [options.token]
   * @private
   */
  _executeScript({actor, token}={}) {

    // Add variables to the evaluation scope
    const speaker = ChatMessage.implementation.getSpeaker();
    const character = game.user.character;
    actor = actor || game.actors.get(speaker.actor);
    token = token || (canvas.ready ? canvas.tokens.get(speaker.token) : null);

    // Attempt script execution
    const AsyncFunction = (async function(){}).constructor;
    // eslint-disable-next-line no-new-func
    const fn = new AsyncFunction("speaker", "actor", "token", "character", this.command);
    try {
      return fn.call(this, speaker, actor, token, character);
    } catch(err) {
      ui.notifications.error("There was an error in your macro syntax. See the console (F12) for details");
    }
  }
```

**Comment by drewg13** [comment]
PF2e system version 4.2.5 fixed this issue.

**Comment by silvative** [comment]
I could go through and change all of the variable names to harden our macros against future changes of this type, if we think it's likely to be an issue again in the future.
