### ISSUE TITLE
Preplaced Kobolds always have Hurried Retreat activated

### ISSUE THREAD

**Issue by Nordiii** [foundryvtt/foundryvtt-premium-content#127]
### What happened?

The Kobolds which are preplaced onto the map always have Hurried Retreat active eventhough the checkbox is not marked.
Checking and unchecking the Hurried Retreat checkbox didn`t change anything.

Replacing the Kobolds with the ones in the Actor tab fixes this.

This was Tested with a new World on:
Foundry: 10.288
PF2E: 4.2.6

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

2.0.1

### Relevant log output

```shell
There are no errors in the consol.
```

**Comment by Nordiii** [comment]
This issue also happens in the Abomination Vaults Module!

Examples on the frist level after a quick glance:
Vampiric Mist
Giant Fly

**Comment by silvative** [comment]
The issue for Beginner Box has been resolved, but it will take longer for the same fix to be applied to Abomination Vaults.
