### ISSUE TITLE
[Bug]: Missing actor (2 Shadow's) in Smuggler's Refuge

### ISSUE THREAD

**Issue by AndeHofer** [foundryvtt/foundryvtt-premium-content#130]
### What happened?

In the scene "Smuggler's Refuge" should be 2 shadows lurking at the cave entry, there are not there. Also there is no shadow actor, only a shadow spawn in 02: The Forgotten Dungeon

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1.0

**Comment by silvative** [comment]
The shadows are not present in the hardcover version of the Abomination Vaults adventure, which is the version that this module is an adaptation of.
