### ISSUE TITLE
[Bug]: Turning off PF2E Beginner Box import "Use Beginner Box Monsters" still imports BB monster tokens

### ISSUE THREAD

**Issue by JulieWinchester** [foundryvtt/foundryvtt-premium-content#131]
### What happened?

The Beginner Box imports Beginner Box monsters, even if you toggle "Use Beginner Box Monsters" off. Turning "Use Beginner Box Monsters" off results in full PF2E actors being imported for the monsters used in the beginner box (like the giant rat with its filth fever disease), but the tokens on the enhanced maps still represent BB-version monsters. 

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

2.0.1

**Comment by silvative** [comment]
I was unable to reproduce the issue with an import into a fresh world on the latest build

![image](https://user-images.githubusercontent.com/66365038/206826941-89d18980-84f2-4aa6-bef4-6a9e9e447214.png)
