### ISSUE TITLE
[Bug]: J02 Arrow Slits are backwards

### ISSUE THREAD

**Issue by ChaseDonnally** [foundryvtt/foundryvtt-premium-content#137]
### What happened?

Honestly, this is such a minor cosmetic issue, but I figured I would post it in case any changes are ever made to maps in the future.

The arrow slits in J02 are backward! The wide side should be on the interior, with the narrow side on the exterior (otherwise they would funnel incoming projectiles toward the archers.)

For a real-life example (on wikipedia):

[Interior of an arrow slit](https://en.wikipedia.org/wiki/File:Arrow_slat_corfe_castle.jpg)
[Exterior of an arrow slit](https://en.wikipedia.org/wiki/File:Bargate,_June_2014_(8).jpg)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.2.0

**Comment by silvative** [comment]
Good eye! A little embarassed I missed that.

Fixing this one will require adjusting the map image asset and then changing walls to match.

**Comment by narchymaps** [comment]
Updated foreground layer provided.
