### ISSUE TITLE
[Bug]: Minor CSS update suggestions

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#142]
List of minor CSS issues which don't require their own issue.

- **Suggestion**: Style the h4 block within the `<section class="compartment">` blocks to match aesthetics of the h1

![image](https://user-images.githubusercontent.com/66365038/200186160-6bfc5f3f-9122-42c8-88c5-9cab2edc2087.png)

- **Suggestion**: Consider hiding page edit button to prevent users making modifications that will be overwritten on reimport. Leave option to edit journal page from right clicking it in the table of contents for determined users.

**Comment by silvative** [comment]
- **Suggestion**: Remove numbers from the journal's table of contents.

Rooms and locations are given numbers by the PDF and in cases where these do not line up it sows unnecessary confusion and adds no additional functionality. This is especially notable since the journals start counting at 0 instead of 1 and there are places where we intentionally condensed locations, such as the Otari town locations, where it would be impossible to achieve parity. 

![image](https://user-images.githubusercontent.com/66365038/200187058-271be611-3524-4ed4-88e3-e9a721d6e81b.png)

**Comment by silvative** [comment]
- **Bug**: Custom background is only applied to page view (edit mode), not journal.
![image](https://user-images.githubusercontent.com/66365038/200388062-f0be3274-1b93-4c0b-9315-aa9d8a4667e9.png)

**Comment by anathemamask** [comment]
Completed as requested
