### ISSUE TITLE
Remove references to BB rules from the Creating Your Hero journal

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#19]
In GitLab by @matthew.l.wheeler on Apr 25, 2022, 13:32

Tried making a character using just the journal entries in the Beginner's Guide and was left scratching my head. The heritage/ancestries which you're instructed to drag and drop onto the sheet don't automatically adjust ability scores and there is no reference as to what scores to adjust and by how much in the journal entries. There are also no instructions on how to get equipment added (the class kits buried in the compendium aren't referenced in the journal or the linked to wiki article) and there is no reference for how much starting money to get.

**Comment by silvative** [comment]
I've chosen to resolve this issue in our V10 update by limiting references to the Beginner Box specific ruleset and focusing specifically on the core rules, which are those that the PF2E system actually supports. With increasing automation system-side in each update, the need for a simplified ruleset is more or less removed, and it serves only to create confusion.
