### ISSUE TITLE
[Bug]: Tokens with errors (Aberrant and Bestial folders)

### ISSUE THREAD

**Issue by Zullock** [foundryvtt/foundryvtt-premium-content#196]
### What happened?

Neothelid - The tongue is cut out.
![image](https://user-images.githubusercontent.com/29728598/208249900-cca9c75e-f9c9-461d-a696-efc7799d3d68.png)
Inculitis - The ring has an error on the bottom 
![image](https://user-images.githubusercontent.com/29728598/208250216-efdacaf9-48ed-4cb5-804a-70eb2666937c.png)
Baomal - To token is cut out on the left side
![image](https://user-images.githubusercontent.com/29728598/208250286-54972955-e363-4314-914b-e9d72c1627ef.png)
Sasquatch - White left around the right hand
![image](https://user-images.githubusercontent.com/29728598/208250871-1b95768f-8804-43da-829b-658bf2a5a7c4.png)

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.1

**Comment by anathemamask** [comment]
sasquatch resolved, reported issue with incultis is just part of the token ring for tiny tokens.
