### ISSUE TITLE
[Bug]: Issue with longer titles in page headers

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#198]
Can we make it shrink the text to fit rather than newline? I'd rather avoid changing the titles for these

![image](https://user-images.githubusercontent.com/66365038/208451452-d3ec1fdd-8e61-4a13-8382-8f4aa9f8cd40.png)

![image](https://user-images.githubusercontent.com/66365038/208455813-edf12d1d-68e7-4e02-a40b-8f4f0761c287.png)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

**Comment by anathemamask** [comment]
Overall font size change to keep it to fit will be required. I'll ponder it.

**Comment by anathemamask** [comment]
Issue caused by system-level CSS specificity taking precedence over ours. Have reapplied ours with more strict specificity.

**Comment by silvative** [comment]
Solution has had unintended consequeunces when combined with page headers that are on subordinate levels (example of level-2 header)

![image](https://user-images.githubusercontent.com/66365038/209994904-dfdeead1-ca45-487e-a69d-2cd8767c558e.png)

**Comment by silvative** [comment]
(Related- the line under the header image doesn't seem correct)
