### ISSUE TITLE
Vostolean inconsistencies

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#204]
### What happened?

Reported by `@Jordi#2571`

Vostolas' actor sheet doesn't match his biography in name or alignment, there may be other inconsistencies, please verify and correct.

![image](https://user-images.githubusercontent.com/26660743/210105214-b1d60a6e-46d8-43a4-babc-639896a320b6.png)

### What package are you reporting this for?

A House Divided

### Version

1.1.1

**Comment by CodeMoWerser** [comment]
Alignment is aligned, titles retitled
