### ISSUE TITLE
Scorncrow abilities do not match encounter text

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#205]
### What happened?

Text for Scorncrow encounter does not align with actor abilities, specifically his ranged attacks and some questions have surfaced about size, legendary abilities, etc. Please verify between encounter and actor and correct.

### What package are you reporting this for?

A House Divided

### Version

1.1.1

**Comment by CodeMoWerser** [comment]
Corrected weird ability data in harbinger ability
