### ISSUE TITLE
Un-check "Use Beginners Box Monsters" has actors with Attacks and Passives still using the Beginner Box version

### ISSUE THREAD

**Issue by IcedEagle** [foundryvtt/foundryvtt-premium-content#215]
### What happened?

When un-checking "Use Beginners Box Monsters", the monsters that are placed in the adventure are not the actual Beastiary versions, as the Attacks and Passives are still the Beginner Box versions (unknown if other stats or items on the Main tab are affected, that is just what I've noticed so far).

When looking at the "Notes" section of the monsters though, it does say it's from Pathfinder Beastiary as expected, and the Notes text is from the Beastiary, so it seems like the monsters are some hybrid of Beastiary and Beginners Box.

As an example, this is the Giant Rat at the very beginning of the adventure. For this monster, note the Passives at the very bottom of the sheet.

![image](https://user-images.githubusercontent.com/934801/212503762-e479526f-8eea-4ce3-b8b0-1310c60e98d2.png)

The Kobold Warrior, also on Floor 1 is missing a Ranged attack that is only in the Beastiary version, and not on the BB version. Have not checked other monsters beyond those two.

Repro steps:
1) Create a new world
2) Enable the PF2E Beginner Box
3) Un-check "Use Beginner Box Monsters"
4) Once imported, go to Floor 1
5) Compare the Giant Rat or Kobold Warrior that is placed on the map, with the version that is in the Beastiary compendium.

Expected: All monsters match their Pathfinder Beastiary compendium versions

Actual: The Passives and Actions at a minimum match the Beginner Box versions, even though they claim to be Beastiary versions

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

2.1.1

**Comment by IcedEagle** [comment]
This is technically a dupe of #131 , however that was closed, and it should be noted that the screenshot showing the source in the character sheet is only half the story. That is correct in that it says it comes from the Pathfinder Beastiary. It's only when you look at the actions that it is not accurate that it came from the Beastiary, and did indeed come from the BB primarily. That Notes tab is not where the issue shows.

**Comment by silvative** [comment]
I'm sorry to hear that I may have closed the issue erroneously. However, I am still unable to reproduce this one. Here is a fresh import with "Use Beginner Box Creatures" disabled:

![image](https://user-images.githubusercontent.com/66365038/216700806-7c210d6e-8d70-4128-8c04-a4cce35b9f63.png)

It's possible that I have fixed this on dev but that it's broken in release, but it's also possible there is another variable (like a module conflict) preventing the importer from functioning correctly. Unfortunately, my ability to diagnose that is limited if I cannot reproduce the issue.

**Comment by IcedEagle** [comment]
Is there other info I can provide? I was able to repro this on latest stable Foundry (10.291) and latest PF2E system (4.6.8) with latest BB module (2.1.1).

I was able to repro both on my Linux machine as a server, and on my Windows install (the video below is from my Windows install).

For what its worth, the Customize World Details is also not working for me (I believe I saw in the Discord that they thought it was a core Foundry bug).

Video repro showing new world and only BB module active:

https://user-images.githubusercontent.com/934801/216717485-d848a4b1-df86-43c7-a046-742943014d43.mp4

**Comment by silvative** [comment]
The "customise world details" button not working is a known issue- we're looking into how best to resolve that.

For the creature stats, I think that the best thing to do would be to wait until our next release (hopefully coming later this week) and see if the issue is still present. At that point you'll be on the same version as me, so if you're still experiencing the issue, we'll know that we need to look further into it

**Comment by IcedEagle** [comment]
@silvative This now works as of the 2.2.0 update! And Customize World Details works too! Great fixes, thanks!

Closing.
