### ISSUE TITLE
[Bug]: AV: Incorrect avatar art for Lallizanx (ch 6)

### ISSUE THREAD

**Issue by scole66** [foundryvtt/foundryvtt-premium-content#218]
### What happened?

The avatar artwork for Lallizanx (in chapter 6) is using the generic Drider artwork, rather than the custom NPC artwork. (The token, however, is fine.)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

2.0.0

**Comment by mattexdee** [comment]
I've corrected the art in the latest version (3.1.0) so I'll close this issue.
