### ISSUE TITLE
[Bug]: Gatewalkers Forest House doors missing

### ISSUE THREAD

**Issue by DawidIzydor** [foundryvtt/foundryvtt-premium-content#233]
### What happened?

Doors are missing in the Forest House between areas A6 and A7 and A6 and A5. There's an art of the doors but there's no doors on the wall layer

### What package are you reporting this for?

A House Divided

### Version

1.0.0

**Comment by TikaelSol** [comment]
Gatewalkers is made by Sigil, so the reporting for issues with that module should go to them instead:
https://support.sigil-services.com/. That said this issue already fixed and will be in the next update of the module.
