### ISSUE TITLE
Merisiel is not trained in Medicine

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#24]
In GitLab by @promise-engine on May 31, 2022, 15:41

Looks like the provided Merisiel isn't trained in Medicine and the PDF Merisiel is.

This was puzzilng me since she has Healer's Tools, so it would make sense that she could Treat Wounds!

**Comment by silvative** [comment]
The issue doesn't clarify which version of the iconic character this bug is present with, but either way it is feedback that should be provided to the core system rather than to the premium content module as the actors used are pulled from system compendiums.
