### ISSUE TITLE
[Bug]: Errant line under Ghost Commoner

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt-premium-content#247]
### What happened?

![image](https://user-images.githubusercontent.com/106829671/219532862-fd751c39-064c-45eb-9552-42462b36bdbe.png)

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.4

**Comment by silvative** [comment]
Note to self, I might want to remove the drop shadow from her hands as well, or at least tone it down
