### ISSUE TITLE
Beginner Box HTML includes some nbsp; or <0xa0> characters instead of standard spaces

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt-premium-content#25]
![image](http://gitlab.com/foundrynet/pf2e-beginner-box/uploads/e3fe58c6fec94dfd2423fd1ff2d2ea6b/image.png)

**Comment by silvative** [comment]
I believe these were required with TinyMCE. I can't see them in V10 with Prosemirror, so I think this one may have resolved itself?

![image](https://user-images.githubusercontent.com/66365038/187247748-8f0caa5d-a5d1-4b5a-8054-e4ab90566461.png)
