### ISSUE TITLE
[Bug]: Pf2e-Beginner-Box - Ezren Pregen missing gold pieces

### ISSUE THREAD

**Issue by Carlosjrlu** [foundryvtt/foundryvtt-premium-content#253]
### What happened?

Ezren Pregen is missing 8 gold pieces as the paizo PDF suggest.

![image](https://user-images.githubusercontent.com/20954701/221487179-5ad9498b-05e3-41d5-846d-d16b631c469f.png)

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

2.2.0

**Comment by silvative** [comment]
The Beginner Box actors are sourced from system compendia and not created by the module, so this is likely a PF2E system issue.
