### ISSUE TITLE
[Bug]: No Haunts with BTs seem to have them listed

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/foundryvtt-premium-content#255]
### What happened?

Several Haunts like the VENGEFUL FURNACE don't have their BT listed along with their HP and Hardness.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

2.0.0

**Comment by silvative** [comment]
This is likely to be a PF2E system issue, unless the haunt statistics are correct in the compendium?
