### ISSUE TITLE
[Bug]: Clerical errors in Chapter 2, 3, 5, 6, 7, 8 and 9.

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/foundryvtt-premium-content#257]
### What happened?

**Chapter 2**

- In B29 there aren't any notes for which trap is A, B, C, D, E. Or which one is the Tsunami, Burning City, Earthquake, monster and undead uprising
- On the map, no visual note for B34, that the elevator goes down to C22

**Chapter 3**

- In C29,  to the south of it, there is no note on the map that the stairs going down leads to D1
- In C36, Candriu's Remains has the Librarian's key
	- When in fact only Jarelle's remains should have the Tiny Iron Key
	
**Chapter 5**

- Within E4 there should be a note on the map that it goes down to F6
- E20- Shuffling Scythe Blades- Reset and Scythe Shuffle 1 through 4 the areas are wrong. They mention Map B when it should be Map E
- Technically speaking, per the rooms description. The Doors for E23 should all be locked. However, there is nothing of value in each one. So whatever.

**Chapter 6**

- In F06 the treasure token Dissection Chamber Detritus should be placed and hidden in F06
- In F21 the ghasts should be elite 
- Per the rules of F24, Barbazu's hell forged glaive attack should have the D10 Deadly trait

**Chapter 7**

- The Hellforge Barabuz's glaives (For Barbazu Vanguard, Hellfroge Barbazu and Barbazu Drill Sergant) should have the D10 deadly trait instead of D8. See in G03, G05 and G10.
- G4a. map label is missing
- In G11 for the Paralyzing light trap under Stasis Field states area D15, when it should be area G15
- On the map, the notes for G19 and G20 are in the wrong place. They need to be swapped with each other other.

**Chapter 8**
- In H8, Dulac and the Owb should be in the same room. The non-secret room. As they described as: _"Custodian Dulac and the owb are in here in close conversation."_
- In H16 Note, the following is missing from the second paragraph: _"Creatures: The three unmarked cages are empty and open. A “c” indicates a cage with a chuul, a “k” indicates a cage with a krooth, and an “s” indicates a cage with a skeletal hulk that was once a Large reptilian humanoid."_
- In H16, there are no labels for: S, C, and K.
- Default token image for Child of Belocrra is wrong, it is selecting Cynemi
- Iribo's avatar image is wrong, points to a drow shootist 
- On the map, the notes H30 and H31 are in the wrong place, they need to be swapped. 
- On the map, the note for H36 should be shifted down south. Out of the two secret doors area. It's placement implies that note is only for that secret door section.

**Chapter 9**

- I- Urdefahan camp map:
	- The mushrooms in the upper right hand corner are missing the lighting.
- I - Hunting grounds map:
	- South of I-38 is missing a door note to say : "To I-34"
	- I51, the mace within Ravirex's hoard is a normal mace. When it should be a +2 Striking Mace.
	- I52/I53, For the Blast Tumbler Trap, the  title for the Stealth DC says 42 when it should say 32.
- In I - Yldaris:
	- I15, the north door is not drawn on.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

2.0.0

**Comment by silvative** [comment]
Thanks for the detail! I couldn't reproduce all of these but I think it may be that they've been fixed as I have closed other issues. I'm going to get all the ones I could reproduce fixed :)

**Comment by silvative** [comment]
As a note, a good number of these were PF2E system issues that are outside of my power to control- especially things like the room numbers in the hazard stat blocks. The stat blocks come from the PF2E system and are using the non-hardcover map names. The numbers still line up but the letters are off. Similarly, things like the attacks on the barbazu are not determined by the module but inherited from the system.
