### ISSUE TITLE
[Bug]: Graphic issue around the token artwork

### ISSUE THREAD

**Issue by Arthil11** [foundryvtt/foundryvtt-premium-content#258]
### What happened?

For the Kobold Warrior assets, both the art and the token, there is a white outline around the artwork remaining. Examples attached.
![image (99)](https://user-images.githubusercontent.com/127357313/223872871-ba049765-9a9e-4148-b478-1ac1c5ea1880.png)
![image](https://user-images.githubusercontent.com/127357313/223872876-9fdd262c-b528-4a5a-bb55-e4150e281576.png)

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.4

**Comment by anathemamask** [comment]
Completed, though please note that while we do what we can to remove white bordering on the creature art pieces in some cases it isn't feasible.
