### ISSUE TITLE
[Bug]: Token Pack Water Yai is too small in combat tracker

### ISSUE THREAD

**Issue by simonward** [foundryvtt/foundryvtt-premium-content#262]
### What happened?

If you add a Water Yai to the combat tracker in PF2e, the icon is too small.

<img width="553" alt="Screen Shot 2023-03-12 at 1 07 41 AM" src="https://user-images.githubusercontent.com/1904698/224535436-7a356254-b021-4c1a-8a10-3bc5053fb175.png">

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.4

**Comment by silvative** [comment]
This is an unfortunate consequence of how our scaling works. The "popout" works on the canvas, but the combat tracker isn't aware of it, so any tokens with "popout" scaling will appear smaller relative to their allies. I wish it wasn't the case, but sadly it's not within scope of the module to change how this works.
