### ISSUE TITLE
[Bug]: Token Pack Black Scorpion has a red tint

### ISSUE THREAD

**Issue by simonward** [foundryvtt/foundryvtt-premium-content#263]
### What happened?

If you add a Black Scorpion to the map in PF2e, the token has a red tint.

<img width="493" alt="Screen Shot 2023-03-12 at 1 15 09 AM" src="https://user-images.githubusercontent.com/1904698/224535561-27bb9011-8ff4-43cf-9da7-f6362af10eb5.png">

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.4

**Comment by silvative** [comment]
The red tint is present in the source asset, but we had recoloured it to match the creature's name. It seems that got reverted, oops! Fixed.
