### ISSUE TITLE
[Bug]: Merisiel is missing training in medicine

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt-premium-content#265]
### What happened?

A user submitted this in email so I don't know if it's accurate or not:

> The included Merisiel PC is missing training in Medicine. That's all.

I also saw it mentioned on the Paizo boards and that user mentioned that it prevents using a treat wounds macro.

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

2.2.0

**Comment by silvative** [comment]
If the iconic is supposed to be trained in Medicine this will be a system bug, since the actors in the Beginner Box are not created by the adventure
