### ISSUE TITLE
[Bug]: Macros containing deprecated functions

### ISSUE THREAD

**Issue by Freeze023** [foundryvtt/foundryvtt-premium-content#267]
### What happened?

the Macros "East Balcony Collapse" and "Archivist Hall Balcony Collapse" contain the function Item#roll which will be unsupported from DnD5e 2.4 in favor of Item#use

Not sure if that has been reported or not, but a cursory glance at the issues didnt show it.

### What package are you reporting this for?

A House Divided

### Version

1.1.2

### Relevant log output

```shell
commons.js:1703 Error: Item5e#roll has been renamed Item5e#use. Support for the old name will be removed in future versions.
Deprecated since Version DnD5e 2.0
Backwards-compatible support will be removed in Version DnD5e 2.4
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Item5e.roll (item.mjs:768:19)
    at Macro.eval (eval at _executeScript (foundry.js:20080:16), <anonymous>:58:6)
```

**Comment by mattexdee** [comment]
Closed as fixed by the latest release 2.2.0.
