### ISSUE TITLE
[Bug]: A journal image filepath breaks in Linux due to case sensitivity

### ISSUE THREAD

**Issue by seiggy** [foundryvtt/foundryvtt-premium-content#283]
### What happened?

Installed & enabled the module, ran the import into my world. When it launched the journal entry for the walkthrough, there's a broken link on the "Perform a Harrowing" page (link has "pf2E-decks-harrow" for the path when it should be "pf2e-decks-harrow").

/modules/pf2E-decks-harrow/assets/journals/harrow-1.webp

Broken on Linux hosted instances of Foundry due to path case sensitivity.

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1.0.1

**Comment by silvative** [comment]
Thanks for this report! At least one always slips in... I'll have it fixed for our next release.
