### ISSUE TITLE
Remove stray pixels present in source assets to clean up all card assets

### ISSUE THREAD

**Issue by Seiak** [foundryvtt/foundryvtt-premium-content#284]
### What happened?

Of the few cards I've check I noticed that there are two small dots in the lower right of the card, I suspect this has originated from the frame layer which has then been baked into each card when they were exported. (Or however they were created, I'm no pro at image editing). If the cards were created in a non destructive manner it should be easy enough edit the frame and re-export all the cards.

I've included screenshots of this.
![image (1)](https://user-images.githubusercontent.com/125596528/236318869-20c31d37-3850-481f-9005-ae13865ee38a.png)
![image (2)](https://user-images.githubusercontent.com/125596528/236318882-76d1d6dd-6474-4503-b4a8-b76614c4736d.png)

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1.0.0

**Comment by anathemamask** [comment]
fixed in commit 29fc37db1892786d6d64bd36b1f37baf0ad743e4
