### ISSUE TITLE
[Bug]: Harrow Deck - Not possible to choose from all cards in preparation step

### ISSUE THREAD

**Issue by JensChup** [foundryvtt/foundryvtt-premium-content#285]
### What happened?

After creating a Reading and Choosing a Suit, it should be possible to drag&drop any card to one of the nine positions. However, if the card does not match the chosen suit, an error is shown "The card does not belong to the correct suit".
As the chosen suit does only limit the cards that can be drawn in "The Choosing", but not the cards from "The Spread", the preparation of the spread should allow all cards.

As example, try to recreate the Reading from the "A Sample Harrowing": The chosen suit is Crowns, and the spread should reveal "The Owl, The Marriage, and The Cricket" in the first column - those cards are from the suits Stars, Crowns and Keys. Only The Marriage can currently be placed.

![image](https://user-images.githubusercontent.com/85436512/236321977-b3c4291d-be4c-4044-80d2-b9693da4e23e.png)

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1.0.1

**Comment by silvative** [comment]
This issue should definitely be addressed. It would presumably be resolved by https://github.com/foundryvtt/pf2e-decks-harrow/issues/31 and has been marked as a duplicate thereof
