### ISSUE TITLE
[Bug]: Fudged readings appear to sometimes result in cards not being present in the final reading

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt-premium-content#286]
### What happened?

while playing with the harrow deck I fudged part of a reading. when I stepped ahead to the Choosing, one of the cards disappeared.

I suspect that one of my fudged cards was the card that originally was drawn for that position. I didn't fudge the position of th emissing card.

![image](https://user-images.githubusercontent.com/74384067/236323052-ad5f81b3-a6f1-4c99-9e02-ba068eda6f5f.png)

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1.0.0

### Relevant log output

```shell
-
```

**Comment by Drental** [comment]
it's the other way around. This time I fudged the Paladin in the top left and it just vacated its spot to move elsewhere!

![image](https://user-images.githubusercontent.com/74384067/236324408-d9d58f69-f454-4874-ac37-df770d9b8f0b.png)

**Comment by aaclayton** [comment]
I believe this issue is fixed (based on my own testing) for the next version release but would appreciate some confirmation that you don't observe the same behavior once our update is available.
