### ISSUE TITLE
[Bug]: Spread limited to single suit

### ISSUE THREAD

**Issue by Lesrek** [foundryvtt/foundryvtt-premium-content#287]
### What happened?

If choosing a suit for the choosing, it limits "the spread" to that suit.  A typical harrow would be...

1. Choose suit for choosing
2. Remove 9 cards of that suit
3. Perform Choosing
4. Shuffle those 9 cards back into the deck of 54
5. Deal 3x3 for "The Spread"

Step 4 currently does not happen.  If the spread is limited to a single suit, it is known ahead of time what 9 cards will be there.

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1

**Comment by silvative** [comment]
This is the expected outcome with the release version of the deck, but will be amended in an upcoming update. For now I am closing this issue as a duplicate of https://github.com/foundryvtt/pf2e-decks-harrow/issues/31
