### ISSUE TITLE
[Bug]: 'D06 - Bath' Macro Doesn't Play Sound

### ISSUE THREAD

**Issue by Urumii** [foundryvtt/foundryvtt-premium-content#292]
### What happened?

When clicking the macro within the journal entry, the water appears and disappears correctly, but no sound is audible.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

2.0.0

**Comment by silvative** [comment]
Hello! The sound for this one is an ambient sound placed on the map, so it's not played through the playlist like other sounds are. The sounds will only be audible if you have a token selected that is near to the bath, so if you are just testing you will not hear anything. If you do have a token placed, you or your players might have the volume turned down very low for ambient sounds? I often do!
