### ISSUE TITLE
[Bug]: world details don't get updated when the option is selected

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt-premium-content#300]
### What happened?

Hi Cora,

I found the issue in my own module and another in yours. Good news: You don't have the issue that I had.

also good new: I got the exact code fix and tested it too :grin:

the handler should use the world.id and grab the response for the update. - there are a few deprecations in there still, but I don't think those matter really.

```js
        if ( !enabled ) return;
        const module = game.modules.get("pf2e-abomination-vaults");
        const worldData = {
          action: "editWorld",
          id: game.world.id,
          description: module.data.description,
          background: option.background
        }
        const response = await fetchJsonWithTimeout(foundry.utils.getRoute("setup"), {
          method: "POST",
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify(worldData)
        });
        game.world.data.update(response);
```

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.0.0

**Comment by mattexdee** [comment]
This issue has been fixed as part of 3.1.0!
