### ISSUE TITLE
AV: Customise World Details setting does not work

### ISSUE THREAD

**Issue by DamnDude030** [foundryvtt/foundryvtt-premium-content#305]
### What happened?

As it states in the title, when I select the option to let the Abomination Vaults AP automatically customize my Log In Menu, it does not do that. I have the entire menu options set to its default state (IE not putting in a background image, not minimal Log In Menu Style) and this is me being on Version 11. I did not test if AV did this in Version 10. 

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.0.0

**Comment by silvative** [comment]
We should also test the Beginner Box as part of investigating this

**Comment by mattexdee** [comment]
This has been fixed as part of 3.1.0!
