### ISSUE TITLE
[Bug]: Original Scenes Do Not Import If "Use Enhanced Maps" Is Unchecked

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#308]
### What happened?

Replication:

- Create new world
- Import adventure
- Uncheck "use enhanced maps" 
- Only the initial landing page will be imported

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/713cb832-42d8-4ab0-97e8-829bbf6f2c16)

### What package are you reporting this for?

Pathfinder: Abomination Vaults
Not tested: Beginner Box

**Comment by mattexdee** [comment]
Closing because it's now possible to import the original maps as part of the 3.1.0 update.
