### ISSUE TITLE
[Bug]: Multiple creatures with weak/elite template are not at max HP.

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/foundryvtt-premium-content#311]
### What happened?

I found the following creatures are not at max HP. The ones I found have either the weak or elite template applied.

"Violet Fungi" in room C23.
"Lasda Venkervale" in room D09.
"Stone Golem" in room J05.
"Dread Wisps" in room J08 and J20.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.0.0

### Relevant log output

```shell
Foundry Virtual Tabletop: Version 11 Stable, 11.304
Game System: pf2e, 5.1.0
```

**Comment by mattexdee** [comment]
Each of these creatures should now have the proper HP configured as part of 3.1.0.
