### ISSUE TITLE
AV - Inline save in journal J15 has wrong type.

### ISSUE THREAD

**Issue by TikaelSol** [foundryvtt/foundryvtt-premium-content#316]
### What happened?

The save in journal J15 is `@Check[type:fort|dc:27]`, it should be `@Check[type:fortitude|dc:27]`

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.0.0

**Comment by mattexdee** [comment]
Closed as it has been fixed as part of 3.1.0.
