### ISSUE TITLE
[Bug]: If a token's size is linked to actor size and modified by a rule element, the importer will overwrite their "base" size with the current value which thus persists even when the rule element is removed

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#32]
In GitLab by @sorrythatuserbla on May 25, 2022, 13:56

See Title.  
Also not sure if this is not a System or Core bug, since I encountered the same behaviour when creating the effect myself for my game.

**Comment by Fyorl** [comment]
> The issue appears to be that calls to `Actor.createDocuments` and `Actor.updateDocuments` are made with arrays of `ActorData`, causing any prepared data to become saved.

Passing `ActorData` shouldn't be an issue here. `ClientDatabaseBackend#_preCreateDocumentArray` will call `toObject` on them, which should not include any prepared data (unless you call `toObject(false)`, which `_preCreateDocumentArray` does not).

The rule-element-modified actor size is somehow being written to the token's `_source.actorData`, which is being persisted in the adventure when it is built. I can reproduce it reliably with the following:

1. Drag a Corpselight token onto the scene from Abomination Vaults > 01: A Light in the Fog > Creatures
2. Double-click the token and open its token actor sheet.
3. Drag the 'Effect: Corpse Claim - Skeletal' effect onto the sheet from Abomination Vaults > Effects
4. Observe the token changes size.
5. Observe the token's source data is correct via the following checks:
```js
_token.document._source.actorData; // Contains only `items` override and nothing else.
_token.document.toObject().actorData; // Same as above.
_token.actor._source.system.traits.size; // {value: "tiny")
_token.actor.toObject().system.traits.size; // Same as above.
```
6. Close the token actor's sheet.
7. Observe that the new size has been persisted to the token's `actorData` by running the above checks again.

I need to do some further investigation to understand if this is specific to the PF2e system, or if it is a core bug around unlinked token actors.

**Comment by Fyorl** [comment]
Fairly confident this issue is specific to PF2e and their rule element system. I'm not able to reproduce it using an equivalent active effect.

**Comment by Fyorl** [comment]
Raised issue in the pf2e repo here: #4955
