### ISSUE TITLE
[Bug]: Area E13, mimic is in the wrong spot

### ISSUE THREAD

**Issue by RahzDM** [foundryvtt/foundryvtt-premium-content#321]
### What happened?

The adventure states that "A pair of mimics recently entered this room. One settled in the northeast corner, disguising itself as a weapon rack identical to the one in the southeast corner." The weapon rack and mimic are placed in teh southeast corner rather than the northeast.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

2.0

**Comment by mattexdee** [comment]
In the 3.0.0 release this appears to already be fixed.
