### ISSUE TITLE
[Bug]: Foundry v11 - All artwork for Pathfinder Token Pack: Beastiaries loses artwork

### ISSUE THREAD

**Issue by sesopenko** [foundryvtt/foundryvtt-premium-content#324]
### What happened?

After upgrading to Foundry v11, the Pathfinder Token Pack: Beastiaries module loses all of its token artwork for all creatures in the beastiary pack.

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.6

**Comment by silvative** [comment]
Hi, I'm reading this issue as meaning that the Bestiary compendiums are not getting tokens and portraits set automatically when the module is enabled in V11. However, I can't reproduce this issue. It's possible that you're using an outdated version of the module or that there is a module conflict or some other incompatibility- I would suggest ensuring that your system and module are up to date, and seeing if you still have the problem in a fresh world with all other modules disabled.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/6ebf7dd5-237e-459a-9bba-c69738ce7385)

For now, I've marked the issue as nonrepro, but please get back to me with more detail if you are still experiencing it or if I haven't correctly understood the issue you're encountering.
