### ISSUE TITLE
[Feature]: Set adventure's keys as "stacks with coins" or change their item type to prevent users from accidentally selling them

### ISSUE THREAD

**Issue by bennyty** [foundryvtt/foundryvtt-premium-content#325]
### What happened?

A lot of the keys in it seem to be created as treasure items (including the pieces of Urevian's pendant) which, uh, causes them to be deleted when you click the "convert treasure to coins" button.

System keys were fixed around this time: https://discord.com/channels/880968862240239708/880969253765935174/1097565259767763096

Reported again here with brief discussion following it: https://discord.com/channels/880968862240239708/891395262810034176/1139272697604481104

As a stop-gap measure, rather than reentering and relinking all the keys as equipment, GMs or AV authors can mark the keys as "Stacks with Coins". This leaves them as Treasure items but the system will not sell them. I mention this because I've combed through issues here for how to manually patch my own world since I don't want to reimport.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.0

**Comment by silvative** [comment]
I've added the "stacks with coins" value to the keys that were set as treasure & the pendants!
