### ISSUE TITLE
Unlinked tokens break on import

### ISSUE THREAD

**Issue by TomChristoffer** [foundryvtt/foundryvtt-premium-content#327]
### What happened?

A bug happened! Unlinked tokens that are imported with the scenes don't receive their actions, their weaknesses and skills and attributes are all there but the actions are blank. 

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

**Comment by silvative** [comment]
I can't reproduce this issue with the latest version of the module- can you confirm that it's still present after updating the module and system? If so, we may need to investigate further.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/f836ef94-6b0d-4284-84c9-831aecbdda89)
