### ISSUE TITLE
[AV] Two NPCs have link actor data on in prototype token settings

### ISSUE THREAD

**Issue by TikaelSol** [foundryvtt/foundryvtt-premium-content#328]
### What happened?

Vethris and Gorsalthith both have their actor data linked in their prototype token settings, breaking the default expectations for how NPC tokens should work.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

**Comment by silvative** [comment]
Closed in dev!

**Comment by Peach774** [comment]
Hey, this is also the case for Iribos, Padli, and Dulac on the same floor.
