### ISSUE TITLE
[Bug]: Unable to Unclaim Hex

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt-premium-content#332]
### What happened?

Trying to Unclaim any hex by simply unmarking the checkbox and hitting save is not reflected.

Tried:
- Ctrl+F5
- Using on Chrome
- Using on Edge

Was also reported by other users in the PF2e Foundry discord

![image1](https://media.discordapp.net/attachments/1152333950451200042/1156657813163085834/image.png?ex=6515c508&is=65147388&hm=f516518b66212b875500cf25838233ba7800de781bed18172925b5d44476978c&=&width=677&height=463)
![image2](https://cdn.discordapp.com/attachments/1152333950451200042/1156657813452505159/image.png?ex=6515c508&is=65147388&hm=a58fa87dfe8d7960ffab6bb14ea694ad3edf7d4eeed7ac7b5a2c209b7e1b8ef1&)
![image3](https://cdn.discordapp.com/attachments/1152333950451200042/1156657813754478693/image.png?ex=6515c508&is=65147388&hm=0457758382fef57b8a3339add0105ca61f011b46f79f76aaed50102e12faeea5&)

Issue is due to _updateObject's "Prune false-y flags", removing those keys when false and thus not updating.
```js
/** @override */
  async _updateObject(event, formData) {
    formData = foundry.utils.expandObject(formData);
    formData.features = formData.features ? Object.values(formData.features) : [];
    const state = KingmakerHexData.cleanData(formData, {partial: true});
    for ( const [k, v] of Object.entries(state) ) {
      if ( !v ) delete state[k];  // Prune false-y flags
    }
    kingmaker.state.updateSource({
      hexes: {
        [this.object.key]: state
      }
    });
    await kingmaker.state.save();
  }
```

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0

**Comment by mattexdee** [comment]
Thanks for the callout. I've fixed this locally and it will be included in our first patch!
