### ISSUE TITLE
[Bug]: Prince Valiant font broken

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt-premium-content#334]
### What happened?

Fon't appears to be broken, same was displayed on the unboxing livestream. Appears to happen on every browser.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/2012848/2e6d8ee7-76c8-4c9e-9945-167f74bb53ff)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0

**Comment by mattexdee** [comment]
This has been fixed and will be included in our first patch. Thank you for calling it out!
