### ISSUE TITLE
[Bug]: Lighting issue in The Beast's Den

### ISSUE THREAD

**Issue by InfamousSky** [foundryvtt/foundryvtt-premium-content#335]
### What happened?

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/88115652/4d0bd273-111f-4403-999e-4af90ff69412)
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/88115652/884173f4-a30a-4bcd-89cf-c9eddf00f5a1)

100-degree light is misplaced resulting in weird shadows

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0

**Comment by mattexdee** [comment]
Fixed and will be included in our first patch. Thanks for the callout!
