### ISSUE TITLE
[Bug]: Improper Token Alliance for Companions

### ISSUE THREAD

**Issue by dylanpiera** [foundryvtt/foundryvtt-premium-content#336]
### What happened?

I reported a similar issue during the Early Access, but it appears that:
- Amiri is marked as 'Party'
- Valerie is marked as 'Opposition'
- Linzi is marked as 'Opposition'
- Iron Wraiths are marked as 'Opposition'
- Everyone else in the room is marked as 'Neutral'

Everyone should probably be marked as Neutral for concistency sake.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0

**Comment by mattexdee** [comment]
All of these actors have been marked as neutral now 👍.
