### ISSUE TITLE
[Bug]: Testing tokens (?) still present on Hargulka's Fortress (Lower)

### ISSUE THREAD

**Issue by InfamousSky** [foundryvtt/foundryvtt-premium-content#337]
### What happened?

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/88115652/8e2eea7b-449a-4d23-ba83-6172db3d72a1)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0

**Comment by mattexdee** [comment]
Fixed and will be included in our first patch. Thanks for calling this out!
