### ISSUE TITLE
[Bug]: Minor data inconsistencies.

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/foundryvtt-premium-content#338]
### What happened?

I found some really, really small inconsistencies in the following areas: 

- Rolltable: "Random Cult Events" can roll for "Urban Outburst" - But the Journal Entry is called "Urban Outbreak".
- Some Playlists don't have a fade time set, like seemingly every other list. 
(Found these two so far: M'botuu Combat, Flickering Jin Durwhimmer)
- Tournament Playlist in "Soundboards" is empty.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.0

**Comment by mattexdee** [comment]
Thank you for the callouts. I've fixed the issues locally and it will be included in our first patch!
