### ISSUE TITLE
[Bug]: Zone Encounters Rollable Tables

### ISSUE THREAD

**Issue by 7H3LaughingMan** [foundryvtt/foundryvtt-premium-content#339]
### What happened?

Some of the roll tables are supposed to roll on a different zone's table if you roll low enough, it looks like several of these weren't setup right. The below example shows that there is nothing there for 1-5. Also for some reason it's rolling a 1d22 for this table so not sure what happens if you roll a 21 or 22.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/117857081/d35782b5-d769-47ba-a068-09935787bf3d)

Also, for some reason Zone 6 is trying to use a Macro to roll for Zone 5 but the macro is missing. You can ignore the fact that I manually set it to 1d5 which was for testing.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/117857081/982cefde-7331-43e4-83ae-953e53a8bfcd)

This last one is just more of a visual thing, but for some reason some of the tables have it set so the icon is a grey dice instead. Not sure if it's because it's rolling on a different table but their are some like Zone 2 which have it black.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/117857081/16b6a394-2c5e-45a6-9089-50a0e4f6bff0)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by 7H3LaughingMan** [comment]
Also, I deleted all the tables and just imported the tables by themselves and they are still that way.

**Comment by mattexdee** [comment]
I've fixed the various roll table issues mentioned here (some were covered by fixes from [this issue](https://github.com/foundryvtt/foundryvtt-premium-content/issues/369)). Thank you for raising them!
