### ISSUE TITLE
Kingmaker Hex Controls

### ISSUE THREAD

**Issue by Pompadorg** [foundryvtt/foundryvtt-premium-content#342]
### What happened?

I accidently Claimed a Hex and now when i uncheck to make it uncllaimed it stays claimed

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.0

**Comment by anathemamask** [comment]
This issue was corrected in version 1.0.1 released earlier today (but probably after you installed it). Please update! :)
