### ISSUE TITLE
Barbtongued Wyvern has a broken token link

### ISSUE THREAD

**Issue by CaptainRoBear** [foundryvtt/foundryvtt-premium-content#344]
### What happened?

Barbedtounge_wyvern's token image is broken because it's in the wrong directory

it's in actor-tokens/kingmaker
instead of actor-tokens/bestiaries
<img width="806" alt="barbedtongue" src="https://github.com/foundryvtt/foundryvtt-premium-content/assets/81845234/4e0e577d-30b9-47ab-91bc-53d8d9c230f0">

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
This token image will now appear as expected in the next release.
