### ISSUE TITLE
[Feature]: Setting to reveal only current hex on map

### ISSUE THREAD

**Issue by jbblanchet** [foundryvtt/foundryvtt-premium-content#348]
### What is the feature?

First of all congratulations, package looks fantastic. A lot of work clearly went into it, and I'm glad I splurged on it.

I was already running the campaign (players just turned level 4), and was using a module called World Explorer to reveal one hex at a time, so players would instantly know what hex they had covered.

Currently, moving the party token reveals both the hex the party arrives on and the 6 hexes around it. I would like a setting to only reveal the current hex, or alternatively a way to manually reveal hexes, similar to what World Explorer does. That would give DMs more control over how they use map reveal.

Thanks and keep up the good work.

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
I've implemented a version of this feature that does seem to function, but I won't close the issue just yet as it'll need to be tested before we release it.
