### ISSUE TITLE
[Bug]: Some tokens have no actor in the world

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/foundryvtt-premium-content#352]
### What happened?

"Slurk" in the Swamp Village Scene has no actor.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/44159008/b095b341-16d6-459a-9162-fa97793deee0)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by tagnullde** [comment]
Same with other Scenes tokens, like "Forest Pond" Scene. The "Loggers" Tokens.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/44159008/28d459a2-e96f-4926-b2db-1031a3f33890)

**Comment by mattexdee** [comment]
These actors are now in the correct folder and will be included in the next release.
