### ISSUE TITLE
[Bug]: NPC Portaits in Social Journals are not Showable to Players

### ISSUE THREAD

**Issue by john-gelinas** [foundryvtt/foundryvtt-premium-content#353]
### What happened?

Portraits in journals are not open-able in the normal popout window that can be shown to players. This is due to the pf2e-km.css line 1675 that prevents clicking on images.

div.journal-sheet.window-app.pf2e-km .journal-page-content section.social aside.token > img,
div.journal-sheet.window-app.pf2e-km .journal-page-content section.social aside.porthole > img {
  pointer-events: none;
}

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
The line is intentional, the images intercepting pointer events is undesireable as it prevents links from being clickable!
