### ISSUE TITLE
[Bug]: Journal entry of Maegar Varn links to unrelated handout.

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/foundryvtt-premium-content#356]
### What happened?

The journal of Maegar Varn (4E0PyKqqYxZhDWcE) links to a letter handout, but not from Maegar but Jamandi Aldori (@UUID[JournalEntry.O3T2uvkYQD6kZOEQ.JournalEntryPage.n4atTj2ZFxzEpvPf]).
It probably should rather link to the journal "Visiting Varnhold" (BAy0CntI5Ct395FN) where Maegars letter is described (last paragraph).

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/44159008/550b0d0a-aa92-4109-82d2-eccf0a93d800)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
Thank you, I've updated the journal with the correct link/text.
