### ISSUE TITLE
[Bug]: The Stolen Lands hex map reveal behavior doesn't match between GM/Players

### ISSUE THREAD

**Issue by Mermut** [foundryvtt/foundryvtt-premium-content#358]
### What happened?

As GM, I moved the party token around the hex map to correctly set the fog of war. When I click on the party token to see it's vision, I see everything the party has been through revealed with the rest the sepia tones. (I also used the hex editor to set the relevant hexes as reconed and discovered.)

I had a player come in and test, and they only saw the areas immedately around the party token (their character was in 'the party' while the party token was being moved)
When I moved the token while the player was in game, the bits they saw stayed revealed... but players NOT in did not see the 'new' terrain.

This behavior is of special concern because A) the map reveals the hex the party is in and all hexes around them (I've found no way to adjust that) AND there is no way to remove vision in individual hexes. This means if the token is mis-moved, it either has to be left or the entire map has to be 're-revealed' WHILE all players are in the game.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by Mermut** [comment]
More details:
During a session, the players see the hexes they've explore correctly colored/revealed.
When they relog/refresh the browser, etc, they lose all color except for the hex 'the party' is on and the surrounding hexes.

The 'revealed' hexes show CORRECTLY for a GM clicking on 'The Party' token, even between refreshes.

**Comment by 7H3LaughingMan** [comment]
Foundry VTT handles Fog of War on a per user basis, so what you are experiencing is due to the current limitations of Foundry VTT.

**Comment by Mermut** [comment]
> Foundry VTT handles Fog of War on a per user basis, so what you are experiencing is due to the current limitations of Foundry VTT.

The fog of war is resetting between refreshes for every single player. If a player refreshes their browser doing the same session.. that player loses all non-sepia toned hex tiles except the hex 'the party' token is on and the ones surrounding it. Between every session the revealed hex tokens reset for all players.
That is NOT normal fog of war behavior on Foundry.

**Comment by Mermut** [comment]
More data: I've tried using actors the players are owners of (other than 'the party' actor) and the behavior is the same for the players.

**Comment by silvative** [comment]
My understanding is that fog is saved for users in their browser (like a cookie) rather than the profile inside of Foundry, so wiping cookies, using an incognito browser, or changing PC will cause fog to "reset". Also, fog explored while a player isn't logged in won't be revealed for them. If my understanding is correct, every issue you're (accurately) describing is an unfortunate limitation of how fog currently works in Foundry, and something that will hopefully be resolved by a core change- since it's beyond the purview of this module.
