### ISSUE TITLE
[Bug]: Kingmaker unable to find or install from manifest on Foundry VTT v11 Build 311

### ISSUE THREAD

**Issue by cdegroat** [foundryvtt/foundryvtt-premium-content#361]
### What happened?

Unable to see Pathfinder Kingmaker under list of worlds to install and attempting to install via manifest here: https://[foundryvtt.s3.us-west-2.amazonaws.com/modules/pf2e-kingmaker/module-1.0.1.json](https://foundryvtt.s3.us-west-2.amazonaws.com/modules/pf2e-kingmaker/module-1.0.1.json)
fails with message: Error: unable to load valid world manifest data from https://[foundryvtt.s3.us-west-2.amazonaws.com/modules/pf2e-kingmaker/module-1.0.1.json]world validation errors: system: may not be undefined core version:may not be undefined

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Hello, please make sure you are installing the module as a module and not as a world! I know it's a little confusing, but Kingmaker includes a lot of custom code and scripts and so on, so it's considered a module rather than a world.

**Comment by cdegroat** [comment]
Thanks, I had just assumed it would be a world, when I installed as module
and added that module to a blank game it let me import everything, so
working perfectly now. Thanks for the response!
