### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by PathfinderBill** [foundryvtt/foundryvtt-premium-content#362]
### What is the feature?

Can we have a way of changing the hex color with the Kingmaker hex management tools? One of my players is very color-blind and is struggling with the red-on-green hex appearance. 
![Screen Shot 2023-10-03 at 11 31 57 AM](https://github.com/foundryvtt/foundryvtt-premium-content/assets/146860744/566040bb-ed2d-4291-831e-9cad595f4349)

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by aaclayton** [comment]
We want this color to be based on the color choice configured by the Party actor - we are waiting for this feature to be supported on the PF2E system side and then it will work to customize the kingdom highlight color based on that choice.

**Comment by PathfinderBill** [comment]
Oh wonderful. Thank you for the quick update.
