### ISSUE TITLE
Winter Overland Map

### ISSUE THREAD

**Issue by PathfinderBill** [foundryvtt/foundryvtt-premium-content#363]
### What is the feature?

Is it possible to get a winter map of the Stolen Lands? It isn't a huge part of the adventure as written, but I love the vibe of heavy snows forcing people to stay in town and ride out the dark months before heading out again. A winter map would be lovely.

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
While I like the idea, I don't think our maps budget has any room left for an entire new version of the Stolen Lands map 😅 We have to carefully consider what we include- download size being another factor to weigh.

**Comment by PathfinderBill** [comment]
I assumed as much, but figured I'd throw it out there. I appreciate all the
work you and your crew are doing. Thanks for the reply.
