### ISSUE TITLE
[Bug]: Kingmaker: "Breeg's Remains" incorrect items

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#364]
### What happened?

In the Hex Encounter, GB2. Dead Trapper, the description of Breeg's remains reads:

> Breeg's hatchet (...) is a cold iron hatchet

The hatchet item in the lootable object is missing the "cold iron" material.

Additionally, he is supposed to have 2 days' worth of rations. In the loot he has 2 packages of 7 days' worth of rations.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
I've fixed both of these issues. Thank you for raising them!
