### ISSUE TITLE
[Bug]: Missing Chew Spider actor

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#365]
### What happened?

The adventure is missing the Chew Spiders actor.

It is linked in the GB18. Fangberry Thicket hex encounter.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
I've moved the Chew Spiders actor into the `3. Stolen Lands` folder so it should be included in our next release.
