### ISSUE TITLE
[Feature]: Add an explanation of the "jump to pin" button to the Hexploration instructions somewhere!

### ISSUE THREAD

**Issue by EndlesNights** [foundryvtt/foundryvtt-premium-content#366]
### What is the feature?

I am completely unfamiliar with Kingmaker and the Stolen Lands, and thus navigating to locations based just on a name is a bit of a challenge. As a result it took me a few minutes to find where a given location or zone are on the Stolen Lands map as the Journal Entry's don't give you any information to go off of. 

A simple soliton that could help with locating the points of interests issue would be to include some basic script macros using `canvas.animatePan` that could just center the your viewport on any given location. Using the following script I added a macro button to all the journal pages. I don't think this might be the most elegant solution but it does greatly ease navigation for a new comer.

```javascript
const stolenLandsMacroFolderID = "bYJ8FaS7q7hC05YX";
const stolenLandsSceneID = "AJ1k5II28u72JOmz"

for(const note of game.scenes.get(stolenLandsSceneID).notes){
  const page = game.journal.get(note.entryId).pages.get(note.pageId);
  if(!page) continue; //There is one Journel Note on the map that is connected to the Intro and not a location. Honestly I think it should probably be removed.

  const macroCommand = `canvas.animatePan({x:${note.x},y:${note.y}});`;
  const macro = await Macro.create({
    name: "Pan: " + page.name,
    type: "script", scope: "global",
    folder:stolenLandsMacroFolderID,
    "command": macroCommand
  });

  const macroInlineText = `<li>@UUID[Macro.${macro.id}]{Pan To}</li>`;
  
  page.update({"text.content":page.text.content.replace('</ul>', `${macroInlineText}</ul>`)});
}
```

As for helping showcase the boarders of the zones, it might be nice if there was a macro that either reveals a tile/drawing image or used Pixi highlighting the boarders of a given zone. As currently to see the boarders of the zone one needs to just wave the mouse around with the Toggle Hex Controls turned on. Which doesn't really particularly great.

### What package are you reporting this for?

Kingmaker

**Comment by aaclayton** [comment]
A reminder that for any JournalEntryPage which has a map pin, you can right click on the page and click **Jump to Pin** which will pan the map to the location

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/2468703/130d3ee3-655b-4258-9ad6-57207a3f3b23)

**Comment by EndlesNights** [comment]
> A reminder that for any JournalEntryPage which has a map pin, you can right click on the page and click **Jump to Pin** which will pan the map to the location
> 

I feel a little silly for never knowing that was a feature. Perhaps if there was an info blog in the Introduction `Reading Foundry VTT Journals` or the `Stolen Lands Exploration` pages that could inform or remind folks that this is a Foundry feature that can greatly help them help navigate around. Or there was some icon next to the Journal/Page that indicated that a scene had a linked note.

**Comment by silvative** [comment]
That's a great suggestion- would you believe I didn't know that feature existed either? We could definitely do to mention it in the journals somewhere
