### ISSUE TITLE
[Bug]: Zone Encounters roll tables are missing links to previous zones

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#369]
### What happened?

Result 1-5 on the "Zone 03: Tuskwater" random encounters table should be a roll on table "Zone 02: Greenbelt", but this link is not present. These kinds of links are missing for zones 02 to 09.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
I've resolved this issue but the `Zone 06` roll table required rolling only a subset of the results from the previous table so I wrote a macro (`Roll Limited Zone 5 Results`) that does that and linked it in the result for easy operation.
