### ISSUE TITLE
[Bug]: TW1. A Delicate Situation is missing logger actors

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#370]
### What happened?

In the TW1. A Delicate Situation journal page, the linked logger actors point to non-existent actors.

This is also the case in the Forest Pond map, where double-clicking the logger actors leads to a warning:
`This Token references an Actor which no longer exists within the World.`

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by theksi** [comment]
I do confirm having the same issue here, on the same version

**Comment by tagnullde** [comment]
Duplicate: #352

**Comment by KazOokami** [comment]
I confirm having the same issue on the same version
