### ISSUE TITLE
[Bug]: Token reference a missing actors on map "Village swamp"

### ISSUE THREAD

**Issue by theksi** [foundryvtt/foundryvtt-premium-content#371]
### What happened?

On the map named "Village swamp" relative to encounter GB11, there is the token of a slurk that has no linked actor and thus canot be opened.
Workaround: 
Replace this token with the token linked to actor named Ubagub

Information: 
Foundry V11.313
PF2e system V5.6.2

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

### Relevant log output

```shell
N/A
```

**Comment by tagnullde** [comment]
Duplicate: #352
