### ISSUE TITLE
Feature: Add maps for locations that didn't have maps in the original adventure

### ISSUE THREAD

**Issue by theksi** [foundryvtt/foundryvtt-premium-content#372]
### What happened?

The Hex GB5 "Frog Pond" contains an encounter against 2 giant frogs, but there is no map for this encounter (as there is none in original book ...) 
This could be a minor improvement to propose a battle map for this encounter

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

### Relevant log output

```shell
N/A
```

**Comment by silvative** [comment]
Although I'm loathe to close a perfectly valid feature suggestion, I don't think it's realistic for me to expect us to add new art assets- or at least nothing on the scale of entire new scenes- to an already-released module, so I'm going to close this one. That said, adding new content is something we are always interested in doing whenever possible, so I promise we will continue to look for opportunities to do that.
