### ISSUE TITLE
[Bug] Scenes for Stag Lord's fort are incorrectly labelled as "Stag King's" 

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#374]
### What happened?

The scenes for Stag Lord's fort are incorrectly labelled as Stag King's. This also applies to the folder's name.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/47220449/cfd14248-639f-4d3e-b16f-3f6009f8e916)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
I've updated the folder and scene's to correctly use `Stag Lord's` instead of `Stag King's`.
