### ISSUE TITLE
[Bug]: Scythe Tree Treasure m issing coins and silver ring

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#378]
### What happened?

The Scythe Tree Treasure actor (from area KL2. The Blighted Hollow) is missing 42 cp, 55 sp, 26 gp and a silver ring worth 7 gp that exist in the description.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
I've updated the loot actor with the correct coins and silver ring.
