### ISSUE TITLE
[Bug]: Hex Encounter KL5. The Mud Bowl missing Tendriculos actor

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#379]
### What happened?

The journal for KL5. The Mud Bowl is missing a link to the Tendriculos actor.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
The Tendriculos actor is linked in the heading of the encounter. This is our typical style when an encounter only includes one creature (or multiples of one type of creature):

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/5018947/d2d217dd-b0cc-4a12-a8de-15e4ff38b87a)

**Comment by Jakub-L** [comment]
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/47220449/e423dfb7-6225-417c-8572-44b5d565de92)
The link does not exist for me

**Comment by silvative** [comment]
Ah, that's not a missing link, it's a broken one- we should move the Tendriculos into the adventure so that it can be imported for Part 1. I'll edit the issue title and we can fix that in the next version.
