### ISSUE TITLE
[Bug]: Ring of Negative Energy Resistance does not have correct rules elements associated

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#386]
### What happened?

The Ring of Negative Energy Resistance (Candlemere Island, location F6. Chamber of the Spiral Seal) does not exist as an item. The journal links to a normal Ring of Energy Resistance, but that item does not give "negative" as a choice of energy type.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Updated the ring to fix it with the new system slug for the negative energy damage type
