### ISSUE TITLE
[Bug]: Teorlian's Valuables loot actor is missing coins

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#387]
### What happened?

Teorlian's valuables is listed as supposed to have 23sp, which are missing from the actor.
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/47220449/ea846786-fbd9-47ea-b3f1-212fb34e94f7)
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/47220449/427b3ddd-41be-4334-8eca-2b8249e9963d)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
Thank you, I've added the missing silver to the loot actor.
