### ISSUE TITLE
[Bug]: The Dancing Lady's Treasure loot actor has incorrect quantities/value of outfits in the wardrobe

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#388]
### What happened?

The Dancing Lady's Treasure (area G8 of the Forgotten Keep) has a container called Carved Wooden Wardrobe that has three errors:
- It has 3 Royal Outfits, where the adventure says 2.
- It has 2 Courtier's Outfits, where the adventure says 3
- Its Several Ruined Outfits are worth 10gp, where the adventure says worthless
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/47220449/5983633e-1a90-4efa-936e-fecf689edceb)
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/47220449/e3a37def-309a-4b72-a5d5-7a4282063f0e)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
Thank you, I've updated the quantities and reduced the value of the ruined outfits to 0.
