### ISSUE TITLE
[Bug]: RL4. Crooked Falls and RL5. Fort Sorenko have their locations swapped. 

### ISSUE THREAD

**Issue by joshuakaras** [foundryvtt/foundryvtt-premium-content#389]
### What happened?

The Stolen Lands scene has RL4. Crooked Falls and RL5. Fort Sorenko swapped. 

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by mattexdee** [comment]
As far as I can tell these notes are in the correct place. From the Kingmaker book (RL4 is Crooked Falls and RL5 is Fort Serenko):
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/5018947/e520b7e6-9977-440e-b123-5c5c407f26a3)

From our Stolen Lands map:
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/5018947/4a0081f5-79c7-4173-b1fb-4daa80d289b3)

Please feel free to reopen this issue if you still think there is a problem. If you can share a screenshot showing what you think is incorrect that would be helpful!

**Comment by joshuakaras** [comment]
Thanks for the reply. Here is the map from book 3 of Kingmaker 
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/39630313/a9365c5d-ffbc-4114-8521-2112376291b1)
Discussions from the errata are here - https://paizo.com/threads/rzs43olf?Kingmaker-Adventure-Path-2E-Errata#1 - James Jacobs has only replied to correct erratas that people proposed that weren't true, which implies that RL4 and RL5 are indeed swapped.
