### ISSUE TITLE
[Bug]: Structures formatting is inconsistent

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#395]
### What happened?

The way structure descriptions are listed (Appendix 2B: Settlements) is inconsistent.
1. In some places the mentioned actions/activities are linked, and sometimes they aren't. Most of these are for the Item Bonus section.
2. In some places the structure name isn't in all caps. The split on these is about 50-50, I wasn't sure whether all-caps or sentence-case was intended, but I assumed it should match the book (which is all-caps)

### **Structures with names not in all-caps:**
Academy, Alchemy Laboratory, Arcanist's Tower, Arena, Bank, Barracks, Brewery, Bridge, Castle, Cathedral, Cemetary, Construction Yard, Dump, Festival Hall, Foundry, Garrison, General Store, Granary, Guildhall, Hospital, Houses, Illicit Market, Inn, Jail, Keep, Library, Lumberyard, Luxury Store, Mansion, Marketplace, Menagerie, Military Academy, Mill, Mint, Monument, Museum, Occult Shop, Orphanage, Palace, Pier, Rubble, Specialized Artisan, Tavern (Luxury), Tavern (World-Class), Trade Shop, Wall (Wooden), Watchtower

### **Structures with activities not linked in the Item Bonus section:**
Academy (Creative Solution), Alchemy Laboratory (Demolish), Arcanist's Tower (Quell Unrest), Bank (Tap Treasury), Castle (New Leadership, Pledge of Fealty, Send Diplomatic Envoy, Garrison Army, Recover Army and Recruit Army), Dump (Demolish), Foundry (Establish Work Site), Hospital (Provide Care, Quell Unrest), Library (Rest and Relax), Rubble (Demolish), Sacred Grove (Quell Unrest), Secure Warehouse (Craft Luxuries), Sewer System (Clandestine Business), Shrine (Celebrate Holiday), Smithy (Trade Commodities), Tannery (Trade Commodities), Thieves' Guild (Infiltration), Trade Shop (Purchase Commodities)

### **Structures with activities not linked in the Effects section:**
Academy (Investigating, Recall Knowledge), Cathedral (Researching, Recall Knowledge), Library (Investigating, Recall Knowledge), Smithy (Craft), Specialized Artisan (Craft), University (Recall Knowledge, Investigating, Research, Decipher Writing)

### **Other issues:**
- Castle: Missing closing parenthesis in the Item Bonus section
- Foundry: Missing closing parenthesis in the Item Bonus section

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Thank you, you're right that there were quite a few minor issues here! I've capitalised all the building names and added links to all the actions I could find. I also went through and made the upgrade to/from fields links to those buildings which should make the experience of using the journal a bit smoother. The last enhancement to make here would be to make the Construction checks into inline @check buttons, which I've created another issue for so that we don't lose track of it.
