### ISSUE TITLE
[Bug]: No Attribute Modifiers on 

### ISSUE THREAD

**Issue by Necrovius** [foundryvtt/foundryvtt-premium-content#396]
### What happened?

The pre-generated Iconic heroes in the Heroes folder, inside the Menace Under Otari folder, under the Actors tab does not appear to have any Attribute Modifiers. This seems to be true regardless of whether the module is loaded with or without using the Beginner Box monsters.

When dragging the Beginner Box Hero actors from the Menace Under Otari compendium, their Attribute Modifiers seem to be assigned correctly. As such, it simply appears to be a problem with the preloaded actors.

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

3.0.0

**Comment by Daeke** [comment]
The bug (and workaround) is that the actors have "manual entry" set by default in their Attribute Boosts.
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/8185349/ad7cb39b-8269-44b0-9038-925c66e47596)

If you open them up and uncheck the box it'll fix the issue!
