### ISSUE TITLE
[Bug]: Typo in the Journal: Zuddager's Picnic in the Supplimental folder should be Zuddiger's Picnic

### ISSUE THREAD

**Issue by ruttzorz** [foundryvtt/foundryvtt-premium-content#397]
### What happened?

On page 425 of the Kingmaker book there's a quest that refers to Zuddiger's Picnic, however the one you have in the Supplimental Journal has an A instead of I in the name.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Oops! Fixed, thank you :)
