### ISSUE TITLE
[Bug]: Fog exploration is reset on refresh

### ISSUE THREAD

**Issue by KazOokami** [foundryvtt/foundryvtt-premium-content#400]
### What happened?

When moving the party token in the Stolen Lands map, the area is revealed just fine, but if I refresh (F5) the page or restart the game, it doesn't matter where the party token is, the hexploration progress is reseted and the map is all sepia again. I've tried disabling all other modules keeping only Kingmaker active, the problem persisted.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by KazOokami** [comment]
after some more testing I've found that when moving the party token repeatedly and randomly, the hexploration progress is saved. But to me it seems random, I can't determine how many movements I need to do so the progress can be saved nor if it's all just a coincidence. Anyway, the hexploration should be saved even if I just move the token 1 hex.

**Comment by anathemamask** [comment]
This may just be a result of how frequently fog exploration saves; perhaps @aaclayton may have some thoughts here.
