### ISSUE TITLE
[Bug]: Map mistakes on Scene "E - Arena"

### ISSUE THREAD

**Issue by dmpunks** [foundryvtt/foundryvtt-premium-content#401]
### What happened?

Caught the following mistakes on the map:

1. In area E01, there is no door-type wall set for the east exit (which is clearly a door)
2. The map journal icons for rooms E14 and E15 have switched locations with each other

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

### Relevant log output

```shell
N/A
```

**Comment by silvative** [comment]
Both of these seem to be fixed on my version- I don't know if the fixes have been released yet, but regardless I'll close the issue and hopefully if it isn't already resolved on our latest version it will be in the next one.
