### ISSUE TITLE
[Bug]: Harrow Deck "stacking the deck" for "choosing." 

### ISSUE THREAD

**Issue by Wisewhun** [foundryvtt/foundryvtt-premium-content#403]
### What happened?

If you stack the deck for The Choosing as the GM, the player is not able to click on any of the 9 face down cards to select their card, the card can only be given to them is (1) they click the "subject card" slot directly, and (2) The GM selects it on their end.

This could make players feel it is stacked since they cannot actually select one of the 9 cards for the choosing.

### Version

1.1.1

**Comment by silvative** [comment]
Oh gosh, no wonder nobody saw this issue- it was labelled with the wrong module! I've fixed that, and I'll see what we can do about a fix for the issue too- hopefully it's as simple as James thinks (thank you for investigating a little!)
