### ISSUE TITLE
[Bug]: Missing/Wrong Information

### ISSUE THREAD

**Issue by KazOokami** [foundryvtt/foundryvtt-premium-content#404]
### What happened?

Number of Web Lurkers on "DS2. Web Lurker Lair". Also, they should be ELITE Web Lurkers
Missing link for enemies on "DS4.Spider Fields"
A17. STOCKADE AND BLOCKHOUSE (Varnhold Vanishing): Text says "DC20 Acronotocs". With this mistyping, the automation for the test doesn't work as there is no acronotocs test in the system.
Missing link for enemies on "Finding Nomen Centaurs"
Missing link for enemies on "LV4.The Ghost Stone"
Missing link for enemies on "C3. Wyvern Bluffs"

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
I've fixed any of these that I could replicate- I'm assuming that the rest were simply already fixed on the dev side before I saw this, but if you notice any of them still present after the next update, please let us know! 
I also ran another sweep through the check buttons for typos and found a few more scattered throughout, and fixed those too.
