### ISSUE TITLE
[Bug]: Rostland Hinterlands encounter table mistakes

### ISSUE THREAD

**Issue by Joshmvii7** [foundryvtt/foundryvtt-premium-content#405]
### What happened?

* Encounter with 2 Brush Thylacines is listed as Low 1 (60). It's actually Severe 1 (120). Can be made Low by removing one Thylacine or reclassified as Severe.
* Encounter with 2 Boards is listed as Moderate 1 (80). It's actually Severe 1 (120). Can be made Moderate by having only one Boar that has elite template, or reclassified as Severe.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
This is a thorny one, but I think it does make sense to fix these issues since they're clearly not intentional choices by the book. I've adjusted the encounters to keep the stated encounter difficulty intact, which I think is the closest to the writer's vision
