### ISSUE TITLE
[Bug]: Sootscale Cavern's B5 treasure is missing contents of the leather bag.

### ISSUE THREAD

**Issue by BloodyChef** [foundryvtt/foundryvtt-premium-content#407]
### What happened?

Treasure pile seems to be missing the next:

"The leather bag contains 21 sp, 9 gp, 1 pp, one dose of dust of appearance, and a plain brass wedding ring set with a single pearl—this is Svetlana’s wedding ring, worth 12 gp as an item of jewelry but far more to Oleg and Svetlana."

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/149866613/cc893118-207a-4f1c-95a7-e08ce9a0eea0)
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/149866613/827c1598-9623-4961-911e-9b7a87948e0d)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
These items were in another loot sheet, and both were correctly linked in the journals, but I've condensed them into the same one since they're found in the same location which should resolve the issue for you anyway!
