### ISSUE TITLE
[Bug]: Kingmaker Hunter actor produces token is named Poacher

### ISSUE THREAD

**Issue by jsavko** [foundryvtt/foundryvtt-premium-content#408]
### What happened?

Result 9-11 on the Zone 01: Rostland Hinterlands Rolltable results with token named `Poacher` when dragged onto a scene from the `Hunter` Actor embeded link

![poacher](https://github.com/foundryvtt/foundryvtt-premium-content/assets/192591/718e2653-fa1c-429e-8f04-99cbf123c0ff)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Good catch! I also editorialised a little and renamed them to "Hinterlands Hunter" to distinguish from the NPC Gallery hunter stat block
