### ISSUE TITLE
Kingmaker - Fetch variants of NPCs

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#409]

**Comment by silvative** [comment]
Stray drop shadow on Amiri:

![Image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/5d0d0986-8b34-41a9-8bfa-01ef36ac25e0)

**Comment by silvative** [comment]
Huh, I think maybe the Fetch Stalker is using the ring from a larger creature? 

I never would have noticed that if I wasn't toggling these effects tbh

https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/2040f60d-db48-45e8-9906-cd060cb6160b

**Comment by silvative** [comment]
For some reason harrim and Jaethal are being made at a different size from the others. Seems to be specific to the artwork- need to check if there is anything different about those

**Comment by anathemamask** [comment]
That's weird on the fetch stalker, jaethal and harrim. 

Jaethal and Harrim's tokens were among some of the earliest made, which might be the source of the discrepancy. Though I thought I sized the fetch tokens based on that; I'll double check when i sit down to do one last round up of tokens.

**Comment by anathemamask** [comment]
Corrected error with fetch amiri as well as fetch stalker token ring.
