### ISSUE TITLE
[Bug]: Missing Token for Tyg-Titter-Tut

### ISSUE THREAD

**Issue by heiroflife** [foundryvtt/foundryvtt-premium-content#410]
### What happened?

Incorrectly uses the basic grig model instead.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by anathemamask** [comment]
Resolved in next version release.

**Comment by silvative** [comment]
Thanks for reporting this- I just added the token and verified that it's being used in the journals & on the actor instead of the default grig token.
