### ISSUE TITLE
[Bug]: Vordakai's Tomb: 2E wall below Xamanthe is not fully closed

### ISSUE THREAD

**Issue by BernhardPosselt** [foundryvtt/foundryvtt-premium-content#411]
### What happened?

The walls are not full closed off in that location

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/195053/089baec6-224d-4da3-8741-763f1c4b63a8)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Thank you, fixed!
