### ISSUE TITLE
[Bug]: Volodmyra fight at end of Chapter 1 has 4 Black Tear Cutthroats rather than 2.

### ISSUE THREAD

**Issue by Joshmvii7** [foundryvtt/foundryvtt-premium-content#412]
### What happened?

Area A23 text says the fight is with Volodmyra and 4 more Black Tear Cutthroats. However, it's listed as a Severe 1 encounter and that makes it Extreme.

The actual combat block on page 38 of the Kingmaker AP PDF has Volodmyra and 2 Black Tear Cutthroats, which matches the intended difficulty of Severe 1.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Oh wow, thank you for raising this one. The text seems to contradict itself ("At the same time, the Black Tears leader, Volodmyra, and four more Black Tear Cutthroats enter the room from the door to the southwest and immediately move to attack the PCs."), but you're right that we should use the number that results in the correct difficulty for the encounter!
