### ISSUE TITLE
[Bug]: Player view on journals has styling issues compared to GM view.

### ISSUE THREAD

**Issue by Joshmvii7** [foundryvtt/foundryvtt-premium-content#413]
### What happened?

The same journals look differently when viewed as a player than as a GM. 
GM view
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/99048395/b37ed7ac-d217-4141-b6cc-3c4185613f91)
Player view
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/99048395/4c4990a4-1110-4edb-9766-fd936292b857)

May be related to issue #341 that was reported about the Kingmaker module.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

**Comment by silvative** [comment]
Oops! That's a good catch- I've fixed it on dev, so it'll go out in the next release.
