### ISSUE TITLE
[Bug]: Broken audio loop for Shrike Hills Theme

### ISSUE THREAD

**Issue by BernhardPosselt** [foundryvtt/foundryvtt-premium-content#414]
### What happened?

audio-music/loops/zone/06 Shrike Hills.ogg is broken at around 1:15; sound just stops abruptly and continues after a couple of seconds of silence

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by anathemamask** [comment]
Looks like an error resulting from how I remixed for the loop. Have resolved for next version release.
