### ISSUE TITLE
[Feature]: Human form for Kundal

### ISSUE THREAD

**Issue by heiroflife** [foundryvtt/foundryvtt-premium-content#417]
### What is the feature?

Kundal, being a werewolf, should have an option to be changed into his human version. Some players are going to likely attempt confront him as a human.

He already has art, so I don't feel like this should be hard to implement.

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by anathemamask** [comment]
Either already completed at time of posting (check assets/actor-tokens/kingmaker/kundal-human.webp) or completed for part 2. :)
