### ISSUE TITLE
[Feature]: Tokens For Questgivers

### ISSUE THREAD

**Issue by heiroflife** [foundryvtt/foundryvtt-premium-content#418]
### What is the feature?

I feel like it would add a lot to the game to have all the questgivers to have tokens ascribed to them. Having them physically show up in the throne room for players to give quests, especially characters like Loy Rezbin (who shows up at the start of the Kingdom), would be a lot more of an immersive experience. 

I'm fairly certain we do have art for all of them, so if its not too much of an issue, that would be appreciated.

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by anathemamask** [comment]
If they have art in the book, they'll have tokens in the module as of part 2. 👍
