### ISSUE TITLE
[Bug]: Rusty Grate Pit in Abomination Vaults is missing the correct DC and trait

### ISSUE THREAD

**Issue by Joshmvii7** [foundryvtt/foundryvtt-premium-content#421]
### What happened?

The Rusty Grate Pit hazard should have a Stealth DC of 20(Expert) or 0 if the grate is open. It currently has just the 0. Additionally, it is missing the Trap trait which tells GMs that features like Trap Finder work with it.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/99048395/a8d9a62b-e37e-483c-9a9d-fa7318da4037)

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

**Comment by silvative** [comment]
Issue seems to have been resolved system-side, which is the source of the stat block!
