### ISSUE TITLE
[Bug]: Freshly Bloomed Basilisk - monster missing

### ISSUE THREAD

**Issue by Crineryr** [foundryvtt/foundryvtt-premium-content#425]
### What happened?

This monster is not added into compendium and relevant entry in the Journal got missing link:
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/123328116/008182ec-39d3-414d-86ce-93eab8a5804f)

Please, add it in the future version.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by anathemamask** [comment]
Corrected
