### ISSUE TITLE
Hex edit window keybind conflicts with attempts to interact with journal notes or tokens

### ISSUE THREAD

**Issue by heiroflife** [foundryvtt/foundryvtt-premium-content#427]
### What is the feature?

I'm uncertain if it is possible to change this, but I often have problems selecting and editing the hex information of the hex my party is currently on (as you have to double click the hex). When attempting to open the hex information it will also open the party sheet as well. This, while not a gamebreaking bug, is frustrating, and often wastes a bit a time.

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by tagnullde** [comment]
It also happens when you have a journal entry on the map. If you double click the journal, it will also open the "edit hex" menu. Would be great if it could be changed.

**Comment by silvative** [comment]
Hmm, I can see how that would be an issue. In earlier versions of the tool, the hex editor and the tooltip used different settings, so they could be toggled separately- perhaps we need to revisit the thought of separating them again. Alternatively, we could change the key combination to open the hex editor, though I'd be concerned about communicating that change to users.

**Comment by silvative** [comment]
Resolved in 2.1.0 !
