### ISSUE TITLE
[Bug]: Hex editor pops up when doubleclicking if the border tool is active

### ISSUE THREAD

**Issue by alexbrault** [foundryvtt/foundryvtt-premium-content#436]
### What happened?

In the Stolen Lands map, the Hex editor opens when double-clicking the map if the border tool is active, even if the Hexploration tool is inactive

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by tagnullde** [comment]
It also pops up when trying to open journals or actor sheets. Would be cool if the Hex Map would "notice" what I try to click (Journal, Actor) and won't open the hex editor regardless of the tool state unless I specifically click on the hex/map.

**Comment by silvative** [comment]
Closing as a duplicate of #427
