### ISSUE TITLE
[Bug]: Importing Kingmaker part 2 into ongoing campaign erases all custom data

### ISSUE THREAD

**Issue by Smithsfan85** [foundryvtt/foundryvtt-premium-content#437]
### What happened?

I'm currently trying to reimport the updated part 2 content for Pathfinder Kingmaker on Foundry VTT but despite unchecking the reset game state box the module is overwriting every custom item I've added to the stolen lands map as well as erasing the party's travel history etc. - is there a way to install and keep the progress made thus far as I've tried twice and both times had to restore my backup. 

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
I definitely agree that there is more that we can be doing to remedy this- I'm combining it with #501 to track the feature request and see what can be done about it.
