### ISSUE TITLE
Map Load-in Dimensions Bug[Bug]: 

### ISSUE THREAD

**Issue by Shadowfire1212** [foundryvtt/foundryvtt-premium-content#439]
### What happened?

On a fresh load of Kingmaker from the Premium Content on the listed maps I get this error message "The dimensions of your configured Foreground Layer image do not match the dimensions of the Background Layer image for this scene. The foreground has been resized which may have undesired results." Then as shown in the example photo all of the characters, effects, walls, and some other things are on the map, however the background of the map is black and nonexistent. 

Current Specs are: 
Foundry VTT Version 11 Stable
Build 315

PF2e 5.11.1

Active Module 1 (Kingmaker: Version 2.0.0)

(Aldori Manor (East), Aldori Manor (West), Aldori Manor (Hall), Aldori Siege (West), Aldori Siege (Hall), Varnhold Blockhouse, Drelev Keep Ground, The Fables)
![Kingmaker issues](https://github.com/foundryvtt/foundryvtt-premium-content/assets/154114307/33150377-14cf-4cf5-82d9-551cc2a93ced)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
Presumably related to #467
