### ISSUE TITLE
[Feature]: correction in AP text

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#442]
### What is the feature?

an error in the AP text, that'd be useful to correct in the module! from ch9 B3 description
`a door stands in the northwest corner.`
it's in the north**east** corner

### What package are you reporting this for?

None

**Comment by dharkus5000** [comment]
this is for KM btw

**Comment by silvative** [comment]
I've added the Kingmaker label to the issue- please make sure to set the module correctly when posting an issue to ensure it's seen!
