### ISSUE TITLE
[Feature]: Moderate Pharasma boon from end of Ch 9

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#445]
### What is the feature?

if you wanted the link you click that links to pharasma's moderate boon (at the end of ch 9) to do something, here's a .json i created that i've tested and works!
[fvtt-Item-pharasma-moderate-boon-zpTVepG83jmfyvkb.json](https://github.com/foundryvtt/foundryvtt-premium-content/files/13721516/fvtt-Item-pharasma-moderate-boon-zpTVepG83jmfyvkb.json)

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
I've folded this issue into #443, so it can be tracked there
