### ISSUE TITLE
[Feature]: Writing on top of Kingmaker Hexploration Fog of War

### ISSUE THREAD

**Issue by Delvoriace** [foundryvtt/foundryvtt-premium-content#446]
### What is the feature?

Hi, I started running the Kingmaker adventure for Pathfinder 2E, and I've run into a bit of a small frustration. I can't find any way to mark the map over the Fog of War to give my players an idea of where they should be going, or show them a point they learn about through roleplay. As it stands, any markings I make on the map is hidden by the fog of war. Is there any way I can draw over it to make it easier to lead them to places?

Thanks in advance!

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by aaclayton** [comment]
Core software limitation that we are working to improve upon in V12+

**Comment by Delvoriace** [comment]
Cool, thanks for the reply. I look forward to the update.
