### ISSUE TITLE
[Bug]: the bloom trophy effect is needlessly complex

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#447]
### What happened?

not really a bug, but the rule elements can easily be combined into 1 rule element, like so
`{
  "key": "FlatModifier",
  "selector": [
    "attack-roll",
    "skill-check",
    "saving-throw",
    "weapon-damage"
  ],
  "value": 1,
  "type": "status"
}`

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
If the rule element functions as desired then I don't believe a change is needed, although it's good to know that there are ways to be a bit more compact!
