### ISSUE TITLE
[Feature]: add an effect for the sounds of Thousandbreaths

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#448]
### What is the feature?

similar to the effect i gave you for howling winds, this effect should be for auditory perception checks, like this
`{
  "key": "FlatModifier",
  "selector": "perception",
  "value": -2,
  "type": "circumstance",
  "label": "Thousandbreaths",
  "predicate": [
    "auditory"
  ]
}`

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
I've folded this issue into #443, so it can be tracked there
