### ISSUE TITLE
[Feature]: Helix Theorem Effect for House at the edge of time

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#453]
### What is the feature?

It'd be useful to have an effect that indicates the effect that the helix theorem has, that can be removed when they do the shed time action
`{
  "key": "FlatModifier",
  "selector": "saving-throw",
  "value": 4,
  "type": "status",
  "label": "Helix Theorem",
  "predicate": [
    {
      "or": [
        "attempt-to-banish",
        "teleportation"
      ]
    }
  ]
}`
speaking of the shed time action, it'd be useful to also have that as an action that can be dragged to PC's Sheets

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by dharkus5000** [comment]
ah, looks like it is an action in the system already, just couldn't see it in the items tab!

**Comment by dharkus5000** [comment]
the action would be useful to be linked to in the description of the effect

**Comment by dharkus5000** [comment]
this rule element could also be added, to have the AC bonus vs the aeons automated
`{
  "key": "FlatModifier",
  "selector": "ac",
  "value": 4,
  "type": "status",
  "label": "Helix Theorem",
  "predicate": [
    "origin:trait:aeon"
  ]
}`

**Comment by silvative** [comment]
I've folded this issue into #443, so it can be tracked there
