### ISSUE TITLE
[Feature]: ch 10 K1b-d would be more useful with K1a, c, d on the map

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#454]
### What is the feature?

as the described combat with the ghostly guards says the guards start in the towers and along the walls, and therefore a combat run as described would have half the ghosts start on the upper lvl, and half of them on the lower lvl, it seems to be that it'd be more useful to have the map section for K1b-d in the same position as it is in the pdf, i.e. to the right of K1a, c & d, so that switching between scenes isn't required to run the combat

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
Hi, unfortunately this change would require a substantial amount of work redesigning the maps, and while I can see how it would be convenient to have everything on one scene, I would personally prefer to see a proper solution that relied on some kind of feature in the core software. Some users choose to install modules to add better multi-level scene support, though of course we can't design around those, and I don't know whether any would be useful in this specific situation. In the meantime, you can mitigate the inconvenience of changing between scenes by ensuring that both are preloaded before you begin the encounter, and of course you're also welcome to create a new scene and place both maps on it side by side if you are confident that your and your players' hardware would be able to handle it.
