### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fougerec** [foundryvtt/foundryvtt-premium-content#456]
### What happened?

On the Stolen Lands map, some of the borders don't completely clear when a hex is claimed.  There's still a red border on only one side of the hex when the surrounding hexes are claimed.  This has occurred in hexes 7.15 (NE), 7.18 (NE), 7.19 (NE) in our game.  Testing shows other hexes along the 7.X row have the same issue.

I tried to attach an image but received an error message.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
Hey, I believe this is a known core bug relating to how the software calculates the edges of hex borders. As far as I am aware, the bug is already fixed for the upcoming V12 core version, and we are expecting that change to fix the issues in Kingmaker when it releases. I'm sorry for the wait!
