### ISSUE TITLE
[Feature]: Add a token for Loris Shadwest

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#458]
### What is the feature?

Loris Shadwest - quest giver of "a flying owlbear" quest, is missing fromthe module, he has a pic on pg 545

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by dharkus5000** [comment]
malchar tevalkan also missing, from quest numerian trade (pg 113), but a pic would have to be created

**Comment by silvative** [comment]
Context for later- no content is missing from the adventure, and Loris's portrait artwork is included at this filepath: pf2e-kingmaker/assets/actor-portraits/npc/loris-shadwest.webp

However, unlike the other questgivers (eg- Jamery Gerbasken), we don't seem to have included a "bonus" token for him.

**Comment by silvative** [comment]
Token has been restored to its rightful position! Keep an eye out for 2.1.0 soon :)
