### ISSUE TITLE
[Feature]: Lantern King Flat check effect

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#462]
### What is the feature?

it'd be useful to have an effect for if the Avatar of the Lantern King gets attacked during the 2 rounds he's laughing, where he roles a flat check for initiative, the following rule element produces that result
`{"key":"AdjustModifier","selector":"initiative-check","suppress":true}`

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
I'm not sure- this is really easy to do manually (you can just right click a roll in chat to use it as initiative), so it would borderline be more work to drag the effect on even if we did provide one. I don't think this one is worth even the minor maintenance burden it would impose on the module. It's also a purely mechanical thing that is more in the system's purview- nothing stops them from automating it already.
