### ISSUE TITLE
[Bug]: Frightened condition is applied to a creature, but not affecting the creature stats

### ISSUE THREAD

**Issue by lobzison** [foundryvtt/foundryvtt-premium-content#464]
### What happened?

I'm not sure if the bug is in the module, system, or Foundry, please let me know if this issue belongs somewhere else

Foundry version: 11.315
PF2e system version: 5.12.3
Abomination vaults module version: 3.1.0

Steps to reproduce:
1. Create a new world
2. Enable the "Pathfinder 2e: Abomination Vaults" module
3. Import the module
4. Switch to the scene "F - Labs", area F10

What is expected:
The "Afflicted Irnakurse" creature has a "Frightened 2" condition, and its stats are lowered
What is happening:
The "Afflicted Irnakurse" creature has a "Frightened 2" condition, but its stats are not affected. Removing and re-applying the condition resolves the issue.

Screenshots:
After the fresh module import
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/31935368/8379ab46-ab95-42a8-b686-9a5b81c1f0c7)
After removing the "Frightened 2" condition. Notice that the stats are the same as after the fresh import
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/31935368/b596d162-7e04-4434-8501-51b30ff53368)
After adding the  "Frightened 2" condition back. Notice the stats are red, and lower than after the fresh module import, even though the token and conditions look identical
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/31935368/39f4c3be-88c7-4a86-af77-d7d55ad0b8f2)

Additional information:
Importing the creature from the compendium is not working correctly as well, the creature has the "Frightened 2" condition visually, but it's not applied

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

**Comment by silvative** [comment]
Interesting- I do seem to be able to reproduce the issue! I think this may need to be resolved system-side, though?

**Comment by silvative** [comment]
I just had a look at this and chatted to the PF2E system devs and I can repro the issue, but it's unrelated to the AV module- it happens even with the module not installed. It seems like a data entry quirk due to the odd edge case of this creature. I've created an issue to track it on the PF2E system's repo [here](https://github.com/foundryvtt/pf2e/issues/14738)
