### ISSUE TITLE
[Bug]: Breeg's cold iron hatchet is standard-grade (value of 968 gp)

### ISSUE THREAD

**Issue by BloodyChef** [foundryvtt/foundryvtt-premium-content#466]
### What happened?

Breeg's cold iron hatchet is standard-grade (value of 968 gp). It probably should be low-grade and value of 44 gp.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
That makes sense to me- change has been made!
