### ISSUE TITLE
Feyward Misaligned Second Floor Wall

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#470]
### What happened?

Originally submitted by geekswordsman
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/26660743/69d6e28d-c01d-4d5f-af61-840fb8ab0a72)

### What package are you reporting this for?

A House Divided

### Version

1.2.0

**Comment by mattexdee** [comment]
Fixed wall placement.
