### ISSUE TITLE
Rolltable errors

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#471]
### What happened?

Originally submitted by nebulis100

"Haunted Echoes" rolltable - each try triggers a "There are no available results which can be drawn from this table". 
"Death Shroud Contents" rolltable, 1d20 missing from Roll table Formula. 

### What package are you reporting this for?

A House Divided

### Version

1.2.0

**Comment by mattexdee** [comment]
Not able to replicate. Presumably fixed sometime before the current 2.3.1 version.
