### ISSUE TITLE
Numerous journal typos and corrections

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#473]
### What happened?

originally submitted by .xao

R03e. East Hallway:
Discrete closet door shows normally, I changed it to a secret door so the players do not see it until they make the perception check

R04. Library:
“early draft of a Letter to Elscieth.” should be “unsent Letter to Elscieth.”

R05. Office:
“An disused tome sitting” should be “A disused tome sitting”

R06. Storage:
“the target of this trap was people opening the barrel, but” should probably be “the target of this trap was not people opening the barrel, but”

R11. Kitchen:
“by naming its token ‘Kitchen Scuttler’.” This is correct on the prototype tokens, but it looks like the tokens existing on the map were dragged out before that because they are still called Rust Monsters
The Rust Monster feature Rust Metal, has a duplicate description on it.
“sink till has a rag” should be “sink still has a rag”

R12. Staff Room
Nitpick: “The door in the south east corner leads into a similar storage closet.” This sounds odd. I had to make a connection that the storage closet had “similar things as the main room”?
Nitpick: “It can be picked with a DC15 theive's tool check.” it would be nice to mention that this door was locked. “It is locked, but can be picked with…”

R14. Dance Hall:
Encounter: It says 2 Poltergeists and 4 Dancers, but there is 1 Poltergeist and 6 dancers on the map
Spectral Dancers: Duplicate Possessive Partner Actions

R15. Parlor: 
"sits at one of the table." should be “"sits at one of the tables."
"within this hall" should probably be “within this room”

Event: Wight Patrol:
“When events turned deadly they didn't even time to respond” should be “When events turned deadly they didn't even have time to respond”
“unique power to raise their victims of their Life Drain attack” could be “unique power to raise their victims with their Life Drain attack”?
Conflicting info: “Wights will generally retreat if their destruction is imminent” but also says “These patrolling wights will fight to the death”

Manor Wight
Their Longsword and Life Drain descriptions have an extra comma “+4 to hit,, 5 ft.,”
The Longbow description does not have the same font bolding of + to hit and range that the other attacks have.

R16. Hallway Landing:
“fibrous mould” should be “fibrous mold”?

R16w. Western Hallway:
Macro: Archivist Hall Balcony Collapse is confusing at first glance. From my perspective it looks like the animations were visible. I realize now that is not the case. Maybe a note about that would help and a note on how to reset by just hiding all of those tiles in that area.

R16e. Eastern Hallway:
“Beyond the floor joists above parts of another hall can be seen,” is confusing, for some reason I read it as through the floor. I changed it to “Beyond the end of the hallway, joists above parts of another hall can be seen,” but I am not even sure I am happy with that.

R18. Western Landing:
“The stone north north wall on the balcony” double north

R19a. The Black Room:
“the overpowering stench of rust and rotting food assaults the nose. with the overpowering smell of rotting food, mildew and rust.” there is an extra period in there, but reading it also feels like the end of the line was rewritten but left in there or something.
Guest Lavatory - I am not sure what this section is describing. Maybe a lavatory was supposed to make it in this room but never did?

R20. The Lord's Chambers:
“succeed in accomplishing their goal, for all they didn't get to live to see it” ‘for all’ is confusing to me. I personally changed it to “even though”

R25. The Royal Suite:
“The door to the closet is closed, but was ransacked a long time ago” makes it sound like the door was ransacked.

General:
The North East stairs in the attic that lead down to the second floor do not have a map note
The Attic South “The South Stair” Map note opens R26 instead of R26c

R26a. The North Hall:
“R26. Servants' Quarters” Should be R28
“R27. Seneschal's Quarters“ Should be R29

R26b. The East Hall:
“R26. Servants' Quarters” should be R28
“ R23c. The South Hall” should be R26c
“ R28. Servants Common Room East” should be R28e

R26e. The West Hall:
“To the west of this hall is a narrow jaunt” I think this is supposed to be “east”
“ R26. Servants' Quarters” should be R28

R28. Servants' Quarters:
“R23a. The North Hall, R23b. The East Hall, and R23e. The West Hall” Numbers should be 26

R36a. Hedge Maze West:
“casting a lot shadow” should be “casting a long shadow” probably

R36c. Memorial Fountain:
“the wood to become swollen” should be “the wood has become swollen”
“ruining of of the fine work” should be “ruining the fine work”

R38. The Great Tree:
“At the base of the tree there is a dull glitter of gold amidst the spider eggs, roots, corpses and cobwebs. Upon closer examination it is a large statuette of a Golden Knight which was probably looted from the manor and lost here.” This text is repeated twice. Just want to make sure something else was not supposed to go in one of the two places.
It is quite confusing which enemies should be in the Colossal Spider fight. It says”Colossal Spider, Ettercap x 2 … and all of the spiders.” and then below that it says “Giant Wolf Spider x 1 and Swarms of spiders.” But then on the map is Colossal Spider, Ettercap x 2, and Giant Green Spider. How often should the Colossal Spider be using Vibrate Webs.

### What package are you reporting this for?

A House Divided

### Version

1.2.0

**Comment by mattexdee** [comment]
- **R03E:** Changed description to refer to hidden passageway.
- **R04. Library:** Fixed at some previous point.
- **R05. Office:** Fixed at some previous point.
- **R06. Storage:** Fixed at some previous point.
- **R11. Kitchen:** Fixed at some previous point.
- **R12. Staff Room:** Resolved.
- **R14. Dance Hall:** Fixed at some previous point.
- **R15. Parlor:** Resolved.
- **Event: Wight Patrol:** Fixed at some previous point.
- **Manor Wight:** Fixed at some previous point.
- **R16. Hallway Landing:** Resolved.
- **R16w. Western Hallway:** Resolved.
- **R16e. Eastern Hallway:** Resolved.
- **R18. Western Landing:** Fixed at some previous point.
- **R19a. The Black Room:** Fixed at some previous point.
- **Guest Lavatory:** There's a lavatory in this hallway with the page pinned to it.
- **R20. The Lord's Chambers:** Doesn't seem to be an issue to me.
- **R25. The Royal Suite:** Not an issue.
- **General:** Fixed at some previous point.
- **R26a. The North Hall:** Fixed at some previous point.
- **R26b. The East Hall:** Fixed at some previous point.
- **R26e. The West Hall:** Fixed at some previous point.
- **R28. Servants' Quarters:** Resolved.
- **R36a. Hedge Maze West:** Resolved.
- **R36c. Memorial Fountain:** Fixed at some previous point.
- **R38. The Great Tree:** Not an issue.
