### ISSUE TITLE
Shadeward foyer overpass tile incorrectly placed

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#474]
### What happened?

Originally reported by .xao

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/26660743/017046a6-3696-4fd7-995d-6be7bb6c79b5)

### What package are you reporting this for?

A House Divided

### Version

1.2.0

**Comment by mattexdee** [comment]
Moved to the correct location and locked.
