### ISSUE TITLE
Toggle Appearance macro fails with error

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#478]
### What happened?

originally submitted by mastertamari

Hello, don't know if this is the correct channel but I'm looking for help with my FoundryVTT game. I'm running the "A House Divided" module, and one of the macros don't work for some reason. Many of the NPCs and Monsters included with the module have a "Toggle Appearance" macro option, but I have been unable to get the macro to execute for any of them. I select the token I wanna use and hit the macro button, but I always get the error "This token does not support shapeshifting" even though the NPCs/Monsters bio says they do have a togglable appearance.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/26660743/7db45ec2-f32c-436a-a48d-34f98bf39aa2)

### What package are you reporting this for?

A House Divided

### Version

1.2.0

**Comment by mattexdee** [comment]
Fixed issues with the Toggle Appearance macro and simplified its execution.
