### ISSUE TITLE
Ochre Geoffrey Split Macro fails with error

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#481]
### What happened?

originally posted by zahariel

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/26660743/a61e4455-2d85-4755-8f6c-5769ec1e00cb)

### What package are you reporting this for?

A House Divided

### Version

1.2.0

**Comment by mattexdee** [comment]
Fixed issue with ochre jelly split macro.
