### ISSUE TITLE
[Bug]: Klarg is missing stats and equipment

### ISSUE THREAD

**Issue by Tex1090** [foundryvtt/foundryvtt-premium-content#482]
### What happened?

Klarg, the bugbear boss in Cragmaw Hideout is missing a completed stat block and equipment.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/52005151/66aee531-2797-4045-a750-612e7bd0dc86)

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/52005151/f1573d88-82eb-4b6f-a857-083b2a9e52e1)

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.0.0

**Comment by aaclayton** [comment]
first blood!
