### ISSUE TITLE
[Feature] Allow partial imports to enable mid-campaign updates of existing content

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#49]
In GitLab by @silvative on May 27, 2022, 06:46

**Problem:**

Module updates to content, as well as in the longer term system updates to actors and items are only available to users willing to reimport the process. Because Abomination Vaults is a long adventure, it may well be that, in six month's time, a user's party have cleared the first six floors and are entering the seventh. Because all content was imported initially, this user's actors for floors 7 onwards would thus be nearly half a year old and several PF2E core versions behind. Without the ability for in-world updates, the average user has no easy recourse to update these actors and must continue to use potentially broken or outdated versions until the end of the campaign.

Their options are: 

**1) Manually delete and re-import the actors to get the new ones.** 

Issue: Because the IDs won't match, this will break all journal links and tokens placed on scenes. They also will only get compendium versions of the creatures without our custom modifications.

**2) Reimport the adventure in place.** 

Issue: Any modifications made to previously imported content will be wiped, affecting not only homebrew but also things like fog exploration, whether or not items have been looted, previously defeated enemies, doors, world state changes reflected by tiles, and other such changes which are a natural result of playing the module. 

While our hypothetical GM may have no plans to revisit the first six floors of the dungeon it would nonetheless be preferable to offer a more elegant solution.

**Suggestion:**

We determined that allowing partial imports could cause potential issues with users experiencing broken links or missing tokens when they only had certain parts of the adventure content in their worlds. However, this issue is not present when *re*-importing content into an existing world that already contains all of this information. Thus, my suggestion is to allow more granular (down to book or chapter level) imports. These could either be locked only to subsequent imports, or available from the start with suitable UX work to signal their purpose. For instance, on the import screen, the setting to import each chunk of content could be checked by default, and unchecking them locked behind unchecking an "import full adventure" or "perform first-time setup" checkbox.

![image](http://gitlab.com/foundrynet/pf2e-abomination-vaults/uploads/13d1bf9d7179c5a1b84ff5bfba6729b6/image.png)

**User Experience:**

Our hypothetical user would, upon reaching floor 7, reimport only book 3 (or only chapters 7-10) and would find their actors seamlessly refreshed and any new bugfixes in the module applied only to the floors they had yet to modify. This would preserve their world's unique state and the actions of their party while also allowing them to benefit from the very latest data from system and module alike.

**Comment by silvative** [comment]
Another thought: Instead of taking the route described in this issue, another potential solution could be a way to make the contents of an adventure visible to GMs in some way. 

In this case, the initial import would serve solely to populate the world the first time. Then, users could choose to open the adventure up and specifically navigate to content they wanted a fresh copy of at any time. This could be used to get a new cop y of a scene if you accidentally broke an old one, to restore an accidentally deleted macro, or to reimport new content selectively after an update.
