### ISSUE TITLE
[Bug] Automated token mapping not working with DND5E 3.0 

### ISSUE THREAD

**Issue by EclipseGS27** [foundryvtt/foundryvtt-premium-content#491]
### What happened?

After the DND 3.0 update, the automated mapping seems to have broken, is there any timeline for this to be fixed?

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.7

**Comment by silvative** [comment]
I'll check with the 5e dev team- I think the D&D system introduced some changes to how they treat tokens recently, but I don't know the details. If that's the cause this would technically be a system bug not a module bug, so it would need to be tracked there.

**Comment by silvative** [comment]
It seems like the 5e system has added a "priority" configuration option for the automatic compendium artwork mapping functionality. Is it possible that the token pack's artwork is disabled in that window for you? If so, can you try enabling it in the system settings and see if that resolves the issue?

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/21ac569d-307d-4fe3-803c-333f7899f89d)
