### ISSUE TITLE
[Bug]: Wall issues in CH 9

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#492]
### What happened?

in Chapter 9 there's a few wall issues
walls instead of doors: northern door to A9 & door between B10 & 11; 
2 wall points not connected but almost connected: in B13 - the left side of the tunnel in the north; part way along the tunnel between B12 & B10 on the right
i've mentioned some previously, hope i haven't doubled up, noticing these as I GM it, it's likely i've not mentioned these before, as i'm noting them as i fix them on my version

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
Thanks for catching these! I've resolved these issues on our end as well :)
