### ISSUE TITLE
All scenes should have their references to a journal entry removed to normalise scene link behaviour

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/foundryvtt-premium-content#496]
### What happened?

In the journal "2. Into the Wild" is a "Encounters" Page under "Part 1. Hexploring the Stolen Lands".
At the very bottom are 3 links to scenes. When clicked they will open a journal page (Central Stolen Lands / Zone 0 Brevoy) instead of the scene.

![Kingmaker-Bug](https://github.com/foundryvtt/foundryvtt-premium-content/assets/44159008/8e1adfe4-55ac-4b2f-889e-1b068351e026)

This bug has been confirmed by others via Discord.

https://discord.com/channels/880968862240239708/996534464970760362/1207062921042067486
https://discord.com/channels/880968862240239708/996534464970760362/1207063973695062078

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

### Relevant log output

```shell
Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: pf2e, 5.13.6
```

**Comment by silvative** [comment]
Seems related to #435

**Comment by silvative** [comment]
It looks like we'll be able to fix this by removing all of the journal entry associations from the scenes, then! Thank you Nath for making that connection
