### ISSUE TITLE
[Bug]: Candlemere Basement Map: The map does not grid nicely... 

### ISSUE THREAD

**Issue by Mermut** [foundryvtt/foundryvtt-premium-content#502]
### What happened?

The image for the Candlemere basement map does not grid nicely (despite the source map in the pdf doing so.)
Hallways have 2 1/2 square rather then  a single full square.
Adjusting the grid since and shifting it still doesn't fix the issue as the image design itself does not seem to have been made 'correctly' to follow a gird.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
It looks like the scene was walled to a very strange grid size- something like 162 instead of the 200 it should have been. I'm not sure how that happened! I've rewalled the scene entirely at its new size, so hopefully that will resolve the issue.
