### ISSUE TITLE
[Bug]: Kingmaker. no access to hex editor

### ISSUE THREAD

**Issue by SpartanDory** [foundryvtt/foundryvtt-premium-content#504]
### What happened?

I don't have access to the hex editor on the Stolen Lands scene
![Screenshot 2024-02-25 at 12-11-33 Foundry Virtual Tabletop](https://github.com/foundryvtt/foundryvtt-premium-content/assets/161245916/b8df664c-961e-4bf4-bf8a-f5dc34aa0f43)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
Hi, it looks like you have a lot of modules enabled that are adding buttons and it's pushing the Kingmaker toolsoff of the screen. Sadly I don't have any way of resolving that myself as I can't control what other modules do- I would suggest either disabling some of the modules to free up space for Kingmaker's tools, or looking for another module that can overhaul the UI to accommodate that many tools (I don't know of any off the top of my head, but I would imagine something like that exists?)

**Comment by SpartanDory** [comment]
It turns out the only issue was with the kingmaker module not showing up in the module management screen until typing kingmaker into the search bar. enabling the module solved the issue for me
