### ISSUE TITLE
[Bug]: Smoking Sword and Shortsword lack a +1 Potency Rune.

### ISSUE THREAD

**Issue by ubik2** [foundryvtt/foundryvtt-premium-content#509]
### What happened?

Both the Smoking Sword and Shortsword lack a +1 Potency Rune.
The PDF indicates that the shortsword in the abandoned storeroom should be a +1 shortsword, but it was just a regular shortsword.
While the Smoking Sword has the fire damage, it didn't have the +1 to hit.

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

3.0.1

**Comment by silvative** [comment]
Thank you for this- I've resolved the issue in our 3.1.0 update!
