### ISSUE TITLE
[Text]: Incorrect actor link.

### ISSUE THREAD

**Issue by Akviel** [foundryvtt/foundryvtt-premium-content#510]
### What happened?

Incorrect actor link in Actor Index journal. (Page 125 - Shambling Mound)
`@UUID[Scene.pbsoMap6p2000000.Token.vlHkpQSD8tcD25Bt.Actor.gGeLeV411iQ5Yijs]`
Need:
`@UUID[Actor.gGeLeV411iQ5Yijs]`

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.0 release](<https://github.com/foundryvtt/foundryvtt-premium-content/discussions/594>).
