### ISSUE TITLE
[Text]: Same location names in the same zone.

### ISSUE THREAD

**Issue by Akviel** [foundryvtt/foundryvtt-premium-content#511]
### What happened?

Journal. Chapter 6. Locations folder: "Gibbet Crossing".
Zones **G12** and **G21** have the same name: "**Receiving Room**"
![Снимок экрана 2024-03-04 020334](https://github.com/foundryvtt/foundryvtt-premium-content/assets/20957999/9279ccee-0c8f-4c38-9993-1ea062829e24)

When translating these adventure pages using a [Babele](https://gitlab.com/riccisi/foundryvtt-babele) mod, it is impossible to correctly translate these two pages into another language due to their same name.
The module cannot translate journal pages within an adventure using the page ID (unless it is the ID of the main journal)

Is it possible to change the original names of these two rooms from the same to different (for example, by adding numbering to them: “Receiving Room 1st” / “Receiving Room 2nd” or something else)?
And also avoid in the future the same page names within the same оournal.

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.1 hotfix patch](https://github.com/foundryvtt/foundryvtt-premium-content/discussions/599) today.
