### ISSUE TITLE
[Feature]: Change wall type of certain walls in Oleg's Trading Post map

### ISSUE THREAD

**Issue by Bhalandros** [foundryvtt/foundryvtt-premium-content#513]
### What is the feature?

Currently Oleg's Trading Post palisade walls are completely see-through from the inside from any distance.

By changing its Sight, Light and Sound restriction to Proximity 5ft. it works as it should; by being see-through only when on the elevated platform next to the walls. (The corners' need 20ft. instead.)

Here's some demonstration.
Current:
![oleg1](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/29ba9bbb-ae16-46fe-9b62-ee8477f6da85)
![oleg2](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/383ce62a-b531-4091-a0ec-0ff87f273090)
![oleg3](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/301ee049-a29a-4b75-bfbd-af72346e1724)
My suggestion:
![oleg4](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/05fc8c05-5964-46c0-af74-b5d5b4967562)
![oleg5](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/b687a7cc-ed68-464d-b465-06609b46c3c0)
![oleg6](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/3c54034e-81cf-4e9a-bbd9-c839ad44837c)
And the corner.
![corner1](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/429755b5-deb7-4bf3-87f4-42075ddd0b26)
![corner2](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/3c616501-a0d4-44db-9f09-a57993988bd8)
![corner3](https://github.com/foundryvtt/foundryvtt-premium-content/assets/27706374/a0062986-eab0-4bfd-8c9f-4504ce70594a)

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
Oh, that's a cool enhancement! We can take a look at doing something like this for sure.
