### ISSUE TITLE
[Bug]: Phandelver and Below - many items with missing or incorrect properties

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#515]
### What happened?

A lot of items are not set up completely.

Most egregious example is the Staff of Defense:

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/69704afe-398d-4c8c-8b3b-8da9e168d1c2)

Along with that,
- none of the Loot-type items have `system.type.value` set,
- many of them have no description,
- none of them have any weight.
- Most do not have a rarity (if applicable),
- almost none have `system.source` set.
- "Sildar's Longsword" somehow has no weight (and is set to "Not Proficient", though this isn't relevant since this property gets entirely reset to `null` when added to an actor).

Additionally seems like some of them should be `consumable`, not `loot` (Emboldening Brandy for example).

Side note: Consider a shorthand for the book title?

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/cb173fd3-ebf4-495b-878f-1f3eec672ff2)

(Dragonguard, bee-tee-dubs, seems to have text pasted with formatting).

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/8b57e43d-c93d-4261-926d-e027d0465c67)

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/10b84077-fec2-436a-a590-0df2c75d9ae4)

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/fd1d0311-3881-49ec-b00e-ba074d2341e3)

A weapon such as Lightbringer should never have a damage formula written in the "Other" field. This prevents the damage from being rolled as critical. The system is limited in this regard obviously, but it would, at least, be functional in the 'Versatile' field. The same is true for the Javelin of Lightning.

Also no magic items have a note in the description explaining their type, rarity, and attunement requirements (e.g., "Weapon (mace), uncommon (requires attunement)").

Incorrect source:

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/50121d61-85a7-4af1-a760-e98156584db5)

This one has actually lost some properties that exist in the SRD; the Magical property, and `system.proficient` being the wrong value. The fact that it is initially unidentified when imported but has no Unidentified description is a minor footnote.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/c6b789a4-c009-41ae-83bb-674d66b119a6)

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/31c55358-7ecf-4c0f-bbb5-7c1fca0ccacc)

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/c4596470-0d3a-4499-831b-f871f4f16c56)

The 'Periapt of Health' item has no effect granting immunity to `diseased`. It's SRD, though, and the issue is there as well, which is probably why. It's also not marked as Magical, but the SRD item is.

The 'Ring of the Orator' is not set up at all. It has no properties whatsoever.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/b233e35d-ad75-47e7-b051-76c612fc99aa)

Usually weapons have no target or just "1 creature", but I guess 'creature or object' is not technically incorrect...

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/ba81c45f-b256-45fe-a79c-fee254c06c38)

The "Blessing of the Solipsistic Mind" has an effect that transfers to the actor by default (and disabled), making duration tracking impossible.

An item will not recover uses when set to charges/dawn/dusk if there is no formula placed in the 'Recovery Formula' field. In this case, the formula should be '1', or it should simply be set to 'Day' instead of 'Dawn'.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/50169243/e256bb5b-7d77-4a61-a63a-90173a9e06be)

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

**Comment by DM-DK** [comment]
In addition, it looks like the prices of magic items are being pulled from the SRD compendium, which is set up with homebrew pricing. Magic item prices should fall within DMG or Xanathar ranges or, preferably, not be included at all. There are other mods we can use if we need homebrew.

Also noticed that the Illustrated Book on Ropers has a price of 2000 gp, but none is listed in the adventure.
