### ISSUE TITLE
[Bug]: Brazier of the Green Flame allows for enchanting magical items

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#516]
### What happened?

The journal describes the brazier as able to enchant any nonmagical weapon or armor. The application should not check that the item has a rarity, which is irrelevant (as per recent changes in the system as well indicating that we agree on this point).

Additionally, the application currently checks for `system.properties.mgc`, which never exists. This was changed to a Set of strings in v3.0.0.

Additionally, the brazier should not allow for enchanting a Natural weapon, only simple/martial weapons.

```diff
- condition: item => item.isArmor && !getProperty(item, "system.rarity"),
+ condition: item => item.isArmor && !item.system.properties.has("mgc"),
```

```diff
- condition: item => !getProperty(item, "system.properties.mgc"),
+ condition: item => ["simpleM", "simpleR", "martialM", "martialR"].includes(item.system.type.value) && !item.system.properties.has("mgc"),
```

Sidenote: this can be completely redone with v3.1.x and the addition of the "magical bonus", but currently it is not functioning as intended.

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.0 release](<https://github.com/foundryvtt/foundryvtt-premium-content/discussions/594>).
