### ISSUE TITLE
[Bug]: Missing check & duplicated damage type in "Goblin Trail"

### ISSUE THREAD

**Issue by arbron** [foundryvtt/foundryvtt-premium-content#523]
### What happened?

On the "Goblin Trail" page in chapter 1, under the heading "Snare", there is a missing check. The text says `"If the characters are searching for traps, the character in the lead must succeed on a check to notice the snare."`, but the actually check isn't included. It should be a `DC 15 Wisdom (Perception)` check.

In the next section under "Pit Trap", the falling damage duplicates the word "bludgeoning".

<img width="683" alt="Screenshot 2024-03-16 at 19 47 55" src="https://github.com/foundryvtt/foundryvtt-premium-content/assets/19979839/56851cc3-8225-4d17-b7cd-b354aab4efd9">

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.0 release](<https://github.com/foundryvtt/foundryvtt-premium-content/discussions/594>).
