### ISSUE TITLE
[Bug]: Ring of Bestial Friendship does not have proper GM text formatting

### ISSUE THREAD

**Issue by ClarissaWinter** [foundryvtt/foundryvtt-premium-content#525]
### What happened?

The Ring of Bestial Friendship on Eirikk's Remains in chapter four: rampage of the beast, does not have proper GM text. 

The text: 
"
The ring of bestial friendship was created by Nyrissa for a specific reason: to allow her pawn Eirikk to manipulate the beasts of the Stolen Lands so as to sow discord among the PCs' nascent kingdom. As long as someone wears it, she can use spells like Discern Location and Scrying on that person as if she possessed a part of their body. This effect does not work in reverse, despite being crafted from a lock of Nyrissa's hair. Instead, any attempt to use the ring as a body part to aid in casting a spell causes the ring instead to explode into a blast of lightning that causes 6d6 electricity damage to all creatures within 20 feet (DC 20 Basic Reflex). This destroys the ring and automatically counteracts the spell effect that triggered the explosion.
"
is currently plain text. This text contains GM-only information, and should be changed to GM text. 

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.0

**Comment by silvative** [comment]
This seems to have been resolved in one of the subsequent system data entry updates!
