### ISSUE TITLE
[Bug]: Some portraits don't have transparent backgrounds

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/foundryvtt-premium-content#528]
### What happened?

Some portrait images in the Beginner Box do not have transparent backgrounds.

I found: 

* Orc Scrapper
* Ghoul Stalker
* Harpy

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

4.0.0

**Comment by silvative** [comment]
This one's fixed in the next update!
