### ISSUE TITLE
[Bug]: Console errors on (re?)import of module contents

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#532]
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/3b42be52-c61d-4478-936a-5639208a0f38)

**Comment by Bendakson** [comment]
Same Problem here

**Comment by silvative** [comment]
I can confirm I'm still getting these in V12, but I don't seem to be seeing any obvious signs of misbehaviour, so it isn't necessary for this to be done as part of the V12 compatibility update. That said, I would like to get to the bottom of it!
