### ISSUE TITLE
[Bug]: G16 Prison Office: Trap is missing actions when opened from token

### ISSUE THREAD

**Issue by AndeHofer** [foundryvtt/foundryvtt-premium-content#538]
### What happened?

When opening from Notes:
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/1547309/2dbd1dc6-771f-4f78-8aba-24b80b6679a2)

When opening from Token
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/1547309/d207b7ef-6e2e-450f-be1e-84fa4710456c)

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.1

**Comment by silvative** [comment]
I don't seem to be able to reproduce this- when I check the token, the actions do display correctly. Is it possible that you accidentally deleted the actions from the token? If so, placing a new token should create a new copy that matches the actor once more. 

If you can reproduce this on a fresh installation using the latest version, I'll need to look further into it, so please let me know!
