### ISSUE TITLE
[Bug]: Image scaling on Juvenile Horned Dragon is wrong

### ISSUE THREAD

**Issue by MothMariner** [foundryvtt/foundryvtt-premium-content#541]
### What happened?

Juvenile Horned Dragon is listed as medium size, but the token scaling on the art is too small to make the token ring fit medium. Currently set to 1.5x, which matches small. To make the ring fill the full medium area it needs to be scaling 2x instead.

Left - adjusted to 2x. Right - fresh from the module, matches the small kobolds in scale.
![Screenshot 2024-04-18 at 00 12 55](https://github.com/foundryvtt/foundryvtt-premium-content/assets/81623344/8009ca85-e5b3-4d16-bad4-795100b37098)

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

4.0.0

**Comment by silvative** [comment]
Oh, good catch! I wonder if he used to be small sized and I didn't notice the change, or if he's been wrong all along.
