### ISSUE TITLE
[Bug]: Polished Shield currently set to offer no AC bonus on raising

### ISSUE THREAD

**Issue by MothMariner** [foundryvtt/foundryvtt-premium-content#542]
### What happened?

The Polished Shield in the module is missing an AC bonus, so when raised does nothing. Edited mine myself, but new GMs and players may miss that it's not doing anything.

Fresh shield with 0 AC bonus:
![Screenshot 2024-04-18 at 00 18 33](https://github.com/foundryvtt/foundryvtt-premium-content/assets/81623344/057c21fd-7970-4486-a4bb-9700e38e2f64)

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

4.0.0

**Comment by silvative** [comment]
Good catch! I'll replace it with a fresh copy of the Steel Shield from the system compendiums.
