### ISSUE TITLE
Token Pack Mapping Change Requests Megathread

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#546]
Compilation of some user suggested changes to mapping
Mapping process was subjective so these aren't guaranteed to get in but I'll consider them, and having them here is better than having people create more issues for each one if there are more

- Hound Archon > Qarna 
EDIT: Symon lied, not a perfect match :c
- Basilisk x Basilisk (No legs)
- Ochre jelly > Tomb Jelly (Scored 3, consider if the description that they can be yellow kicks it to a 2)

**Comment by Symon-S** [comment]
Purple Worm > Cave Worm. Same art, just dyed more grey than purple

**Comment by silvative** [comment]
> Purple Worm > Cave Worm. Same art, just dyed more grey than purple
I leaned away from doing this one because the colour change was done very deliberately- but certainly it's a valid replacement for users to apply themselves.
