### ISSUE TITLE
[Feature]: Nugrah npc spell attack bonus is too high.  [errata request]

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt-premium-content#548]
### What is the feature?

this is more of an errata request as the monster building rules state

 a 'high' spell DC and attack bonus for a level 5 creature is 22 and +14
 
 
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/62528192/556469b0-3597-4af0-b26f-c6b4ea50d05c)
whereas in this image the spell dc is 23 and the attack bonus is +23. which will insta crit anyone of that level.

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
Hmm, this is definitely a mistake for the reasons you point out, but unfortunately the stats do appear that way in the book:

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/aac6f7b2-12e9-4429-a004-082c4a36ba97)

Our actor stats come from the PF2E system, and their data entry team don't deviate from printed stat blocks, so unfortunately without official errata we aren't likely to see a change here. I'll still make an errata request to Paizo- errata for APs is pretty rare, but at least then it'll be on the list if they do ever do some. If that happens, the good news is that as soon as the PF2E system devs get their hands on it, their changes will immediately filter down into the module.
