### ISSUE TITLE
[Bug]: Missing/incorrect token/subject images

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/foundryvtt-premium-content#566]
### What happened?

- various tokens are missing or have a "token" path as their Subject Path (`flags.dnd5e.tokenRing.textures.subject`), so always use a static token
	- Quasit (missing)
	- Circle of Wildfire (uses token path)
	- Clay Spirit (uses token path)
	- Night Hag (uses token path)
	- Soulknife (uses token path)
- Water Elemental uses default dnd5e token, despite Water Elemental files being included (looks like the same issue as #495)
- `assets/subjects/circle-of-wildfire.webp` has token ring pre-baked into subject image

### What package are you reporting this for?

Tasha's Cauldron of Everything

### Version

1.0.0

### Relevant log output

```shell
N/A
```

**Comment by mattexdee** [comment]
Completed as part of the [1.1.0](https://github.com/foundryvtt/foundryvtt-premium-content/discussions/600) release.
