### ISSUE TITLE
[Bug]: Zozzlarin on Floor 2 has the generic Zebub portrait

### ISSUE THREAD

**Issue by adyoungblood** [foundryvtt/foundryvtt-premium-content#567]
### What happened?

Zozzlarin's actor uses the generic Zebub portrait from Chapter 6 (modules/pf2e-abomination-vaults/assets/bestiary-portraits/ch-06/zebub.webp), despite having unique art and a portrait in the filesystem (modules/pf2e-abomination-vaults/assets/bestiary-portraits/ch-02/zozzlarin.webp).
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/16092423/9ecd2085-efc9-4738-b57f-522e1efdcbe8)

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.2

**Comment by silvative** [comment]
Good catch! I'll try to fix this for the next update.
