### ISSUE TITLE
[Bug]: Blood Fury Tattoo listed twice in Tasha's Cauldron of Everything.

### ISSUE THREAD

**Issue by tslewis123** [foundryvtt/foundryvtt-premium-content#570]
### What happened?

In the magic tattoos section of Tasha's Cauldron of Everything, the Blood Fury Tattoo is listed twice.

### What package are you reporting this for?

Tasha's Cauldron of Everything

### Version

1.0.0

**Comment by mattexdee** [comment]
Completed as part of the [1.1.0](https://github.com/foundryvtt/foundryvtt-premium-content/discussions/600) release.
