### ISSUE TITLE
Toggle Appearance Macro throws error[Bug]: 

### ISSUE THREAD

**Issue by ghost00-Ricgames** [foundryvtt/foundryvtt-premium-content#574]
### What happened?

Many of the NPCs and Monsters included with the module have a "Toggle Appearance" macro option, but I have been unable to get the macro to execute for any of them. I select the token and click the macro button or directly apply the macro from the journal, but I always get the error "This token does not support shapeshifting" even though the NPCs/Monsters bio says they do have a togglable appearance. This was fixed in a previous drop, but has come back now.

Package 2.4.1
Foundry V111 Stable 315
Only other module installed is Tasha's as I do game prep to learn what A House divided does.
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/122754683/25f16a23-14db-4751-bf3d-d4520645a226)

### What package are you reporting this for?

A House Divided

### Version

2.4.1

**Comment by anathemamask** [comment]
Resolved in forthcoming update thanks to the efforts of @stwlam
