### ISSUE TITLE
Typos in Getting Started Journal Entry

### ISSUE THREAD

**Issue by drewg13** [foundryvtt/foundryvtt-premium-content#576]
### What happened?

# General note:
 - Many Journals variously use "gamemaster", "Gamemaster", and "Game Master", seemingly interchangeably.

# Introduction: Getting Started

### Party Creation Guidance
 - "...starting at level 5 which will advance to level 10...the contents may carry them into the 11th level." is inconsistent with **Plot Synopsis** "...characters should advance from level 5 to level 9." and "These late stages of the adventure will generally advance characters from level 8 to level 9." and with **Milestones and Advancement** "...expected for characters to conclude the adventure at level 9." and "...possible, albeit unlikely, that they will reach level 10 by the adventure's conclusion."

### Audio Recommendations
- "Whether the party is exploring the Ruined manor..."  ->  Ruined Manor

### Act I - Early Game
 - "...and learn that disappearance at Raventree Estate is no simple haunting..." -> that the disappearance at the(?) Raventree Estate

### Act II - Mid-Game
 - "...the party will meet its disfunctional family..." -> dysfunctional

### Act III - Late Game
 - "...and carve their own path - they are tasked..." ->  and carve their own path, they are tasked
 - "...experience one of the adventures many endings." -> adventure's many endings

### Proximity To Civilization
 - "Raventree estate is about three days of travel..." -> either "The Raventree estate..." or "Raventree Estate..." or "The Raventree Estate..."

### Rumors of Unclaimed Land
 - "Looking Into The Rumours" -> Rumors (inconsistent with other usages on the same page)
 - "...is in fact a large swatch of land..." -> is, in fact, a large swath of land (swatch would be an atypical usage here, more likely a [eggcorn](https://www.quickanddirtytips.com/articles/spoonerisms-mondegreens-eggcorns-and-malapropisms/))
 - "...this is the Raventree manor specifically..." -> Raventree Manor

## The Last Heir To Raventree
 - "...My initial proposal is that a simple scouting the manor will yield [[/award 200g]],..." -> enricher failure?

## A New Challenger Appears
 - "Friend Of Foe?" -> Friend Or Foe?

## The Lost Child of Corvinarus
 - "...you pry away the wax and withdrew a collection..." -> withdraw (present tense consistent with rest of block)
 - "...abandoned after some sort of indicent..." -> incident
 - "...birth parent, and that the Raventree manor is to pass..." -> Raventree Manor

### Consequences of Approval
 - "Characters which are fond of you..." -> Characters who are fond of you

### Managing Hostility
 - "...Suppose the party has enraged Lord Kryn and Lady Vivesna who each of -8 approval..." -> who each have

## Navigating the Planes
 - "...planar transit point is used, regardless of where or how one of two events start..." -> is used, regardless of where or how, one of two events
 - 

### What package are you reporting this for?

A House Divided

### Version

2.4.1

**Comment by anathemamask** [comment]
Resolved in forthcoming update! Thanks for your feedback!

**Comment by drewg13** [comment]
I appreciate the fixes!  Some of the misspellings caught my eye and, once I got started trying to clearly document them, I started noticing other things.  I'll point out that this one got missed.  Now that I'm playing with it, it appears that the fix is to change "200g" to "200g**p**".

The Last Heir To Raventree

    "...My initial proposal is that a simple scouting the manor will yield [[/award 200g]],..." -> enricher failure?
