### ISSUE TITLE
FVTT wall section missing outside E12

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#58]
In GitLab by @narchy on May 29, 2022, 09:24

The wall on the west side of the cooridor is missing. 

![1](http://gitlab.com/foundrynet/pf2e-abomination-vaults/uploads/85fd500492a7e6e555f0e6bc0d5eff42/1.PNG)

**Comment by silvative** [comment]
I think this was caught in the last patch, since it's fixed on my end!
![image](https://user-images.githubusercontent.com/66365038/175012680-21e7a047-eb09-42c4-82cf-03213658e557.png)
