### ISSUE TITLE
[Feature]: Set Dynamic Ring Colors

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/foundryvtt-premium-content#582]
### What is the feature?

The active combatant indicator added to the dnd5e system in [#2824](https://github.com/foundryvtt/dnd5e/issues/2824) requires the dynamic ring to have a Ring Color and/or Background Color to display, updating the actors/tokens to have this property would increase visibility of this feature
Perhaps #cd2c1e

Also applies to Tasha's as well, but can only choose one 

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

**Comment by mattexdee** [comment]
We're going to look at a change to how this works in the system so that if the ring color is not set we use something like the user's color instead of setting a color on all of the Actors 👍
