### ISSUE TITLE
[Bug]: Macros using document.data

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt-premium-content#583]
### What happened?

https://discord.com/channels/170995199584108546/1184176344276406292/1250420954962853959

Checked the Macros in chapter 04 and 06 and noticed that in both chapters the `.data` of some document is used. Can you check the macros and update them?

Thanks a bunch,

DrentalBot

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.2

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'hidden')
```

**Comment by silvative** [comment]
Thank you for the pointer on where to start! It seems like just about every single macro outside of Chapter 1 uses .data in at least one place. I've gone through and I believe I've removed them all, I hope I didn't miss any 😅
