### ISSUE TITLE
[Bug]: Journal Text Errors

### ISSUE THREAD

**Issue by trioderegion** [foundryvtt/foundryvtt-premium-content#589]
### What happened?

Content link label error:
Chapter 2 -> Locations: Redbrands Hideout -> What the Redbrands Know -> Prisoners... "(**see area R4 for details**)"

Should read as:
Prisoners... "(**see area R5 for details**)"

Note: The actual linked content is correct (R5), just the labeling is wrong.

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

### Relevant log output

```shell
Discord User: @bad_dm
Message Link: https://discord.com/channels/170995199584108546/1021485757631828030/1247491090928631859

In Phandalin Obelisk, there is a text error.  
The link works, but they were incorrect about which room had the people mentioned.  
Chapter 2 -> Locations: Redbrands Hideout -> What the Redbrands Know -> Prisoners... "(see area R4 for details)" should say "(see area R5 for details)" and also link to R5.
```

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.0 release](<https://github.com/foundryvtt/foundryvtt-premium-content/discussions/594>).
