### ISSUE TITLE
[Bug] E6 & E10 bridges should be modified so they can function as overhead tiles

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#59]
In GitLab by @narchy on May 29, 2022, 09:28

These tiles are designed for being toggled in the background layer, not as overhead tiles. In the overhead layer they are clipping over the foreground layer. 

![3](http://gitlab.com/foundrynet/pf2e-abomination-vaults/uploads/259d581b8653cea61ec2e641911b126e/3.PNG)

![2](http://gitlab.com/foundrynet/pf2e-abomination-vaults/uploads/078566da8373c3836556e12194d24b87/2.PNG)

**Comment by narchymaps** [comment]
Updated tiles provided.
