### ISSUE TITLE
[Bug]: Chapter 2 Scene Token configuration errors

### ISSUE THREAD

**Issue by trioderegion** [foundryvtt/foundryvtt-premium-content#590]
### What happened?

Redbrand Hideout:
* The Token of the Imp Zeond in R11 is not invisible but starts visible
* The Token for Iarno Albrek has Displayed Name set to Iarno Albrek, not Glasstaff, which appears in the tracker, spoiling the secret.

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

### Relevant log output

```shell
Discord User: @bad_dm
Message Link: https://discord.com/channels/170995199584108546/1021485757631828030/1252226508865409034

In Phandalin Obelisk, there are two more errors in Chapter 2:
 - In Redbrand Hideout, the Token of the Imp Zeond in R11 is not invisible but starts visible (ack) 
 - The Token for Iarno Albrek has Displayed Name set to Iarno Albrek, not Glasstaff, so as soon as combat starts, players can see his secret identity in the combat tracker and spoil the mystery
```

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.0 release](<https://github.com/foundryvtt/foundryvtt-premium-content/discussions/594>).
