### ISSUE TITLE
[Bug]: 404 on the Audio Credits

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt-premium-content#593]
### What happened?

Hey Cora, me again!

I don't have the Beginner box installed and checked the Audio credits, and got greeted by a 404

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/74384067/4924e0e0-9734-4a7f-bc1d-663a62c0baf0)

seems to try and display modules/pf2e-beginner-box/assets/audio/powered-by-syrinscape-logo.png

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

**Comment by silvative** [comment]
This one is very funny- a bug I could never have noticed myself, since I would always have both modules installed! I'm choosing to take the fact it's gone unreported so long as a good thing :)
