### ISSUE TITLE
Where are the Custom Hex Exploration Tools?

### ISSUE THREAD

**Issue by Geekfest** [foundryvtt/foundryvtt-premium-content#596]
### What happened?

Not really a bug, just ignorance and an inability to find ANYONE with the answer. I'm desperate for some kind of user guide for the Premium Kingmaker module for Pathfinder 2e. I need a user guide - does it exist? Please!

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.1

**Comment by silvative** [comment]
Hi, I'm sorry to hear that you're having trouble with using the module! I'm sure we can help you with locating the tools you're looking for.

First off, assuming that you aren't encountering a bug, the hex exploration toggles appear in the scene controls (the toolbar on the left hand side of your screen) while you are on the Stolen Lands scene with the Kingmaker module enabled in your world. In the first control group, you should find two buttons (pictured below)- the first one toggles the hex configuration tool, and second one the regional boundaries overlay. If the buttons aren't there, then something isn't behaving as expected, so please get back to me and we can try to sort out your problem!

![image](https://github.com/user-attachments/assets/12ecbd3c-20a7-4aec-8038-78c5eeb262b5)

In terms of documentation, you can find explanations of Kingmaker's special module features in the module's journals, usually in the same journal that goes over the rules for the subsystem they pertain to. For instance, there's some tutorials on how to use our settlement maps and assets in the Settlements appendix journal. The Hexploration tutorials specifically can be found in the Chapter II journal, as that's the chapter that contains the hexploration rules. 

Here's a screenshot showing the specific journal (titled _2. Into the Wild_) and the two relevant pages (_Exploring on Foundry VTT_ and _The Hex Tooltip_):

![image](https://github.com/user-attachments/assets/29ad7345-8c9a-42b6-8661-9f39cf577f58)
