### ISSUE TITLE
[Bug]: Spider Staff Item Enrichers

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/foundryvtt-premium-content#597]
### What happened?

Nezznar's Spider Staff's item enrichers do not work because the spell's names do not match (Note that Glass Staff's Staff of Defense does not have this issue)
Either the spell names should lose the `(from Spider Staff)` or the enrichers changed to include it `[[/item Web (from Spider Staff)]]{Web}`
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/86370342/2a064544-4176-4799-b44d-553decd194ee)

Sidenote, perhaps the Spectator and Beholder's Eye Beams items would benefit from item enrichers too

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.2.0

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.1 hotfix patch](https://github.com/foundryvtt/foundryvtt-premium-content/discussions/599) today.
