### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MulliganStu** [foundryvtt/foundryvtt-premium-content#598]
### What happened?

In chapter one of the actors, there is a token named Wagon, which is a horse image. I was wondering if this was on purpose because it's listed as a land vehicle and has all the inventory of the wagon from the chapter.

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.2.0

**Comment by mattexdee** [comment]
I'm afraid I'm not understanding what the issue is? The Wagon actor uses a horse image because the horse is drawing the wagon (and we didn't have source artwork to use of just a wagon). Please let me know if I'm misunderstanding the issue @MulliganStu.

**Comment by MulliganStu** [comment]
No issue! I was just wondering if that was supposed to be that way or not. Thanks!
