### ISSUE TITLE
[Bug]: Overhead for Bridge macros on floor E no longer works in foundry v12

### ISSUE THREAD

**Issue by JakeRigler** [foundryvtt/foundryvtt-premium-content#601]
### What happened?

When pressing the Bridge macros for floor E, the tokens always walk under the bridge visually, whether the bridge is above or below them according to the macro.

The Macros for the bridges are still using overhead for the bridge tile, which seems to have been depreciated in v12. Changing it to elevation: 0 and elevation: 20 seems to fix the issue. 

I have reimported the macros and tested with no modules

https://github.com/foundryvtt/foundryvtt-premium-content/assets/25049583/74e28047-b5b5-406d-a007-8a3e53fff34f

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

**Comment by alwaysafk** [comment]
This is impacting my tables as well. Exact same issue.
