### ISSUE TITLE
[Bug]: Foundry v12 - Creatures stat blocks dont have actions or reactions on new import

### ISSUE THREAD

**Issue by TheChrisFlowers** [foundryvtt/foundryvtt-premium-content#605]
### What happened?

When I import in v12 the creatures are not populated with the correct stat blocks. The creatures show up in the actors tab, but the tokens on the map are do not have the actions or reactions on the stat block. If i drag from the actors tab, the creatures have the correct actions/reactions.

![miflit import](https://github.com/foundryvtt/foundryvtt-premium-content/assets/26311233/c8d6d5a3-29de-4666-b517-6487b7f659ac)

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

v12

**Comment by silvative** [comment]
I can't recreate this issue in my dev version, so it's possible that simply the process of packing a fresh update has resolved whatever the issue may have been- please let me know if you continue to experience this problem after the update releases and you've had a chance to make a fresh import!
