### ISSUE TITLE
Typo: Description of Shanrigol Undulating Step ability.

### ISSUE THREAD

**Issue by bitvypr** [foundryvtt/foundryvtt-premium-content#614]
### What happened?

The description of the Shanrigol Undulating Step ability, last sentence reads: "It can’t use any actions other than until it occupies an area large enough for its normal form."

It should read: "It can’t use any actions other than *Undulating Step* until it occupies an area large enough for its normal form."

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

**Comment by simonward** [comment]
It looks like this was addressed in the system:
```
commit 674f44f0c748caca1cbed1e619a448e3a3601658
Author: kromko <34245546+Cuingamehtar@users.noreply.github.com>
Date:   Thu May 2 09:52:11 2024 +0300

    Fix some minor description errors (#14571)
```
