### ISSUE TITLE
[Bug]: Unable to import adventure data after V12 updates

### ISSUE THREAD

**Issue by xcmt3** [foundryvtt/foundryvtt-premium-content#621]
### What happened?

Many environmental macros seem to have broken in the V12 update, so I attempted to reimport macros/journals to see if a refreshed version would fix the issue.  However, I am getting an error stating "Cannot read properties of undefined (reading '_types')" and a progress bar that permanently hangs at 1%.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

### Relevant log output

```shell
foundry.js:72042 Cannot read properties of undefined (reading '_types')
fetch	@	foundry.js:72042
foundry.js:6671 TypeError: Cannot read properties of undefined (reading '_types')
    at #i (/C:/Program%20Files/…ocument.mjs:1:11880)
    at Macro.sanitizeUserInput (/C:/Program%20Files/…ocument.mjs:1:11785)
    at Macro.preprocessData (/C:/Program%20Files/…ocument.mjs:1:15353)
    at /C:/Program%20Files/…-backend.mjs:1:4866
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._updateDocuments (/C:/Program%20Files/…-backend.mjs:1:4768)
    at async Semaphore._try (/C:/Program%20Files/…emaphore.mjs:101:17)
_onSubmit	@	foundry.js:6671
```

**Comment by farling42** [comment]
Restart your foundry server.
It seems a general issue, and restarting the server seems to get rid of the _types error.

**Comment by xcmt3** [comment]
You know, I tried that three times yesterday and no dice.  Try it today, and...well...closing this.  Turn it off and on, kids!  And then keep doing it until it works.
