### ISSUE TITLE
[PF2E] [Bug]: Monster Core Token Pack lacks correct Scale settings for all tokens

### ISSUE THREAD

**Issue by SoupcanAnthill** [foundryvtt/foundryvtt-premium-content#625]
### What happened?

I didn't test every single monster, but every one I did test results in incorrectly sized tokens. It seems they are generally set to be scale 2, but the new tokens should be 2.5.

I selected the Bestiaries Token Pack because monster core isn't in the list yet.

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

12.0.1

**Comment by lholden** [comment]
An upcoming release of Foundry (I've heard "this week") is going to be adding a "fit mode" for the Dynamic Rings. This will make them take 100% of the space, which I assume is what this ticket is wishing for. 

https://github.com/foundryvtt/foundryvtt/issues/11571

It sounds like the respective modules will need to get updated before the setting will work with them however. (If they haven't already been by the time this releases).

**Comment by SoupcanAnthill** [comment]
Foundry listened and fixed their (in my opinion) silly goof, so I'll mark this closed.
