### ISSUE TITLE
[Bug]: Issues with character artwork

### ISSUE THREAD

**Issue by bLanark** [foundryvtt/foundryvtt-premium-content#626]
### What happened?

For nyzuros in this folder: pf2e-abomination-vaults\assets\bestiary-portraits\ch-08

There is a lot of weird artifacts/words on the left hand side of the character artwork 
![image](https://github.com/user-attachments/assets/20b1ee73-db18-4932-87c1-a5b2b0e99e1d)
![image](https://github.com/user-attachments/assets/d10425ed-fe28-431a-888b-7b4854aa70e6)

Is it possible to fix this? 

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

**Comment by silvative** [comment]
Wow, even with you showing me where to look, I really struggled to find these! How curious- they must have been leftovers in the original file that none of us noticed, not even when making the tokens. I've erased them from the portrait- good catch! Do let me know if you find similar artefacts on any other assets :)
