### ISSUE TITLE
[Bug]: "Pathfinder Tokens: Monster Core" and "Pathfinder Tokens: Bestiaries" interact poorly

### ISSUE THREAD

**Issue by lholden** [foundryvtt/foundryvtt-premium-content#630]
### What happened?

With just the "Pathfinder Tokens: Monster Core" module installed everything works as expected.
1. The tokens are of the right size - (2/3 subject area, 1/3 outer padding), per the FoundryVTT dynamic token guidelines.
2. The portrait art is from the Monster Core module as expected

When installing both the "Pathfinder Tokens: Monster Core" *and* the "Pathfinder Tokens: Bestiaries" modules, there are some bad interactions.
1. Monster Core tokens have their scales overridden, causing the tokens to be tiny compared to just using the Monster Core module.
2. Monster Core portrait art for ends up coming from the Bestiary module instead of Monster Core, though the token art themselves is from the Monster Core.

LEFT are Monster Core Actors created with *both* installed.
RIGHT are Monster Core Actors created with *just* Monster Core installed.
![image](https://github.com/user-attachments/assets/1304f3b5-bd20-441b-8eab-730e78f25b16)

### What I expect:
The Monster Core module to take precedence for art and token scaling when both modules are installed.

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

Pathfinder Tokens: Bestiaries - 1.1.1
Pathfinder Tokens: Monster Core - 12.1.0
Foundry - 12 330
PF2E - 6.2.1

**Comment by lholden** [comment]
Almost everything here looks to have been resolved with the 1.2.0 release of the Token Bestiaries! Fantastic!

Two problems remain however.

1. When the load order for the art is set to have the bestiaries first before monster core, then the Monster Core unique stuff has no art at all. Fixed by swapping the two. (I only noticed this because the bestiary art default to first priority).
2. The Compendium Browser shows no art at all for any NPC. :).

**Comment by ottyn** [comment]
> Almost everything here looks to have been resolved with the 1.2.0 release of the Token Bestiaries! Fantastic!
> 
> Two problems remain however.
> 
>     1. When the load order for the art is set to have the bestiaries first before monster core, then the Monster Core unique stuff has no art at all. Fixed by swapping the two. (I only noticed this because the bestiary art default to first priority).
> 
>     2. The Compendium Browser shows no art at all for any NPC. :).

For #2, this should be fixed with the PF2e System release.
https://github.com/foundryvtt/pf2e/pull/16066

**Comment by pinkflumph** [comment]
I have a related issue: when both modules are installed, the scale of the tokens _and_ scale correction are both set to 2, resulting in gigantic tokens that overflow from the ring:
![2024-08-19_16-51-58](https://github.com/user-attachments/assets/23527f75-3f7f-4885-a0b8-9cec611ea008)

Setting Monster Core to a higher priority under Settings -> Core -> Compendium Art resolves the issue
