### ISSUE TITLE
[Bug]: Character Gallery: Red Mantis Assassin spelled incorrectly

### ISSUE THREAD

**Issue by TMunsie** [foundryvtt/foundryvtt-premium-content#646]
### What happened?

Red Mantis Assassin is labelled as Red Mantis Assa**sss**in.

![image](https://github.com/user-attachments/assets/5b43af8b-f4c7-45cc-aee9-12a33061b35b)

### What package are you reporting this for?

Pathfinder Tokens: Characters

### Version

1.0.1

**Comment by silvative** [comment]
Adding here- saw Discord report that the goblin smith is also listed as gnome oops
