### ISSUE TITLE
Missing doors between C10 and C11 and C18

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#66]
In GitLab by @BigWyDog on May 31, 2022, 06:59

Missing one door entering from C10 into C11. Missing two doors leading from C11 into C18/C19

**Comment by silvative** [comment]
I've added the former door. The latter two don't appear in my copy of the PDF, though I can see the map features that you are assuming to be doorframes; I'm not exactly sure what they're supposed to be, but it doesn't make any sense to me to have them as doors so I'm leaving them as-is. 

![image](https://user-images.githubusercontent.com/66365038/175004835-05bd52e4-1000-423e-a5a9-f00f3ab0f4a1.png)
