### ISSUE TITLE
[Bug]: Missing "Zealot of Asmodeus" images

### ISSUE THREAD

**Issue by BrotherArius** [foundryvtt/foundryvtt-premium-content#660]
### What happened?

There are no images connected to the "Zealot of Asmodeus" from the NPC Gallery.
More specifically the following file is missing:
gmg-zealot-of-asmodeus.webp

### What package are you reporting this for?

Pathfinder Tokens: Characters

### Version

1.0.2

**Comment by silvative** [comment]
Interesting- I think the Zealot of Asmodeus is the GMG's Inquisitor, I must have included it twice in the datasheet (once under each name) by accident. I'll try to make sure it's deduped from the next version!
