### ISSUE TITLE
[Feature]: Add Polish translate

### ISSUE THREAD

**Issue by Lioheart** [foundryvtt/foundryvtt-premium-content#669]
### What is the feature?

Hi,
I adding Polish translate for Pathfinder Tokens: Character Gallery. Please add to module. Thanks

[pl.json](https://github.com/user-attachments/files/16805607/pl.json)

### What package are you reporting this for?

Pathfinder Tokens: Character Gallery

**Comment by silvative** [comment]
Hey Lioheart! Thank you so much for your work on this. 

We aren't currently able to add non-english language support to our modules natively- unfortunately, we don't have the resources to create them ourselves, nor to proofread or maintain them. We also don't really like the idea of setting a precedent of repackaging the unpaid work of community members, even if they volunteer it themselves. Finally, although it most likely doesn't apply in this specific case, there are also licensing considerations to providing translations of modules using other peoples' IP, where the translation rights may already be held by another party. For example, when we released the German version of the Beginner Box, we partnered with Ulisses Spiele, who own the license for the German translation of that book. Without their involvement, we wouldn't have been able to release that update.

It's possible that in the future we might be able to start including more translations by default in our modules, but in the meantime, the best way to handle this is for the translations to be provided by a third party module. There are a few examples of this, for instance I believe [this](https://foundryvtt.com/packages/lang-pl-pf2e) module provides a Polish translation for the PF2E game system. I think that creating a similar module is probably the best way for you to get your translation to other users, as it would mean we could do it without the additional obstacles presented by including it in an "official" paid module. If you aren't sure where to start with module creation, there's an article on our knowledge base that provides an [introduction to module development](https://foundryvtt.com/article/module-development/), and please do feel free to reach out to us by email and we can try to provide some more precise instructions. Similarly, please do let me know if there is anything I can do on the module side- for instance, any missing localisation strings- to make the process easier for you.

**Comment by Lioheart** [comment]
Hey @silvative,
 
I would like to ask you to add additional strings to the en.json file so that it can be easily translated. Currently it looks like this, as in the image below.
![obraz](https://github.com/user-attachments/assets/16f4caab-3ae8-41fd-b137-7d502d87bd6b)

As you can see, the tags on the left as well as part of the left side do not translate because they are not in the en.json file. If there was a possibility, I would ask you to add their equivalents to the json file or use the names directly from the system.
