### ISSUE TITLE
[Bug]: Several creature macros not working

### ISSUE THREAD

**Issue by hugomarques** [foundryvtt/foundryvtt-premium-content#672]
### What happened?

I have detected several macros are not working. My current version if V12 Build 331. 

For example, the bridge macro on level E does not work. (related to: https://github.com/foundryvtt/foundryvtt-premium-content/issues/601)

In addition to that, so far I have seen:

The mimics macro on room E13 and the bone gladiator macro on room E25 seems to share the same issue:

```
VM6128:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hidden')
[No packages detected]
    at MacroPF2e.eval (eval at #executeScript (foundry.js:20082:16), <anonymous>:9:53)
    at #executeScript (foundry.js:20087:17)
    at MacroPF2e.execute (foundry.js:20028:35)
    at MacroPF2e._onClickDocumentLink (foundry.js:20097:17)
    at HTMLAnchorElement._onClickContentLink (foundry.js:70141:17)
```

After some more debugging, it seems the token id used in the function to execute the script is different from real token id the creature has.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

**Comment by alwaysafk** [comment]
@hugomarques were you able to fix it by updating the macros to the correct tokens?
