### ISSUE TITLE
[Bug]: 2024 PHB Rage Effect cites incorrect scaling value

### ISSUE THREAD

**Issue by alaustin0** [foundryvtt/foundryvtt-premium-content#688]
### What happened?

The 2024 PHB Rage Feature comes with an effect that references "+@scale.barbarian.rage-damage" for its MWAK bonus, but the actual scaling value in the Barbarian class is "@scale.barbarian.rage".
<img width="429" alt="msedge_2QGt9H6Iqk" src="https://github.com/user-attachments/assets/61443c4c-8458-424f-a59f-d3374045de50">
<img width="253" alt="msedge_MLEsrIl7oh" src="https://github.com/user-attachments/assets/984ee9eb-64c8-4727-aa9a-b69bc014cd26">

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by mattexdee** [comment]
Closing because this is fixed in the latest 1.1.2 release!
