### ISSUE TITLE
[Bug]: Species Traits are not added to sheet until you add a Class

### ISSUE THREAD

**Issue by alaustin0** [foundryvtt/foundryvtt-premium-content#690]
### What happened?

Species traits are not added to character sheet through advancement until you add a class item onto the sheet.

Repro:
1. Add Species to new PC Actor (I tested Tieflings + Drow)
2. Add Class item from PHB

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by trioderegion** [comment]
Which species traits are granted at level 1? For example, the Drow should grant all base traits immediately (any level), and the dancing lights cantrip is granted at level 1 explicitly.

**Comment by alaustin0** [comment]
Ah, that's almost certainly what's going on. Thought for sure something was up when I added a class and saw "Tiefling traits" but that explains exactly why that is. Working as intended!

**Comment by trioderegion** [comment]
Excellent, thanks for closing the loop!
