### ISSUE TITLE
[Feature]: Add Unarmed Strike weapon for Monk and non-Monk characters

### ISSUE THREAD

**Issue by alaustin0** [foundryvtt/foundryvtt-premium-content#691]
### What is the feature?

The PHB currently does not have a preconfigured weapon for unarmed strikes. This isn't always a big deal for regular characters, but Monk's not only need an item for that, it needs to be configured to the scaling value, which is difficult to set up for the inexperienced.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by lholden** [comment]
This would be nice. I ended up adding an Attack activity to the Martial Arts feature for this. But it would be nice if this was handled in a more systemic way.

**Comment by Dazaer** [comment]
Completed? Where? I don't see the branch or any logs on this...
