### ISSUE TITLE
[Feature]: Consider removing the saving throw enricher in the Elemental Attunement feature item's description

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#706]
### What is the feature?

It has the saving throw in an activity, and even says as much in the description. An enricher on top, I feel, serves only to confuse. This is also the only item that has a saving throw enricher in the entire compendium.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by mattexdee** [comment]
Thanks for the callout! Before we had activities I built things with these inline just in case and must've missed it when I cleared the others out. Will be fixed in our first update.

**Comment by krbz999** [comment]
Similar damage enricher in Vitriolic Sphere.

**Comment by krbz999** [comment]
The check and fire damage enrichers in the 'Web' spell are arguable, but I'd say the check enricher should be an activity at least.

**Comment by krbz999** [comment]
Same with the psychic damage enricher in the Geas spell.

**Comment by krbz999** [comment]
The 'Weird' spell has the additional save in the activity, so the description can yeet this.
