### ISSUE TITLE
[Bug]: Inconsistent indentation of page markers in Exploration chapter

### ISSUE THREAD

**Issue by ehllie** [foundryvtt/foundryvtt-premium-content#707]
### What happened?

Indentation of the "Travel Pace" page marker, and its sub headings is different than other markers in the "Exploration" chapter.
<details>
<summary> Screenshot </summary>
<img width="294" alt="image" src="https://github.com/user-attachments/assets/23c6ca9f-bb90-4149-9f26-fcef2747781e">
</details>

Should "Travel Pace" be a subsection of the "Travel" page?

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by mattexdee** [comment]
Thanks for the report, but this one is on purpose. Travel Pace is intentionally a separate page for easier linking and embedding of that content without the additional overhead of the Travel page's content. It's using Foundry's built in "Level" feature for journal pages to indicate that it is related to the Travel page above it. You'll see this convention used in a lot of places throughout the book like the Creating a Character journal for example.
