### ISSUE TITLE
[Feature]: Implement Weapon Mastery Statuses

### ISSUE THREAD

**Issue by RFedewa2002** [foundryvtt/foundryvtt-premium-content#708]
### What is the feature?

A request to add statuses like "sapped" and "slowed" to be added to tokens when hit by a weapon with the corresponding mastery. Additionally, that the chat card for weapons with the "slow" mastery property have the arrow to add the status in the same way the "Fear" spell can add "frightened" to tokens easily. Thank you!  

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by mattexdee** [comment]
This is a good request! I've filed it over on the system repo [here](<https://github.com/foundryvtt/dnd5e/issues/4355>) since we'd be implementing it there. Feel free to subscribe to that issue for updates!
