### ISSUE TITLE
[Bug]: Inconsistency between Conjure and Summon Elemental

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/foundryvtt-premium-content#711]
### What happened?

There is a bit of an inconsistently between the Conjure and Summon Elemental spells. Both spells allow you to summon a creature that are of either the air, earth, fire or water element. The Summon Elemental spell is set up to give you 4 choices, while the Conjure Elemental spell gives one template statblock with different attacks for the type you want it to be. Since after summoning you cannot swap the type, why doesn't Conjure Elemental have 4 statblocks to choose from like the Summon Elemental spell? 

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by trioderegion** [comment]
The initial motivation related to the fact that it is only the damage type on the Conjuration that changes and the other Conjure X spells operate with a similar, single Actor.

I can revisit that design, but to help considerations, is the current Actor configuration and how to use the Conjuration unclear? or is it a matter of expectations based on the "choose the type of elemental" spell text?

**Comment by maxobremer** [comment]
To me its a matter of expectations based on the spell text.
Additionally I think it can be helpful in a particularly large battle for some players to immediately see which type they choose based on the token art of the elemental (People can zone out and as the dungeon master I wouldnt want to have to keep track of one of my players summons because they forgot. Or have to scroll up in chat to see which damage type it was again)

**Comment by trioderegion** [comment]
I appreciate the feedback. Thank you.
