### ISSUE TITLE
[Bug]: Duplicated activity on Arcane Vigor spell

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#718]
### What happened?

![image](https://github.com/user-attachments/assets/86814a24-9188-4eff-b43c-bc7b32dcc5d3)

(Sidenote: wondering if this couldn't be improved in the system to not need an activity for each die size but just smallest/largest available. It's probably *currently* best this way because spending 2 hit dice might change what `hd.largestAvailable` actually is.)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by trioderegion** [comment]
The consumption of the last 2 remaining largest hit die and then rolling your smaller, remaining hit die was exactly the issue I was trying to avoid.

Thanks again.

**Comment by mattexdee** [comment]
Closing because this is fixed in the latest 1.1.2 release!
