### ISSUE TITLE
[Feature]: Adjustment to Reincarnate spell

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#719]
### What is the feature?

Would be nice if the spell description had the `rollable` option to the table embed rather than an inline 1d10 roll. This would display the *drawn* result in chat rather than just the total of a d10.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by mattexdee** [comment]
Closing because this is fixed in the latest 1.1.2 release!
