### ISSUE TITLE
[Bug]: Players do not have permission to browse the host file system

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt-premium-content#72]
In GitLab by @mark.pearce72 on Jun 3, 2022, 10:15

Console error for players when joining a game. should check permissions before trying 

![image](http://gitlab.com/foundrynet/pf2e-abomination-vaults/uploads/778f7d5d43d319a2c5bf3c001eb8fdb5/image.png)

**Comment by Fyorl** [comment]
Repro steps appear to be only 'join game as player', and I was not able to reproduce the error following those steps. There also appear to be modules in the stack trace.
