### ISSUE TITLE
[Bug]: Battlemaster uses the wrong formula for Combat superiority

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/foundryvtt-premium-content#728]
### What happened?

The amount of uses for Combat Superiority is set to @scale.battle-master.superiority which gives 4d6 as a result
@scale.battle-master.superiority.number should be used which gives 4 as an actual number
![image](https://github.com/user-attachments/assets/e1160bf1-5d9b-48d3-b3d7-b48fdd7c7558)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by mattexdee** [comment]
Closing because this is fixed in the latest 1.1.2 release!
