### ISSUE TITLE
[Bug]: Pact of the Blade not using CHA as its attack and damage mod

### ISSUE THREAD

**Issue by zzahringer** [foundryvtt/foundryvtt-premium-content#729]
### What happened?

Pact of the Blade is not overriding the weapon's attack and damage mod with Charisma like it should. As far as I can tell, it's missing those items in the applied active effect.

To reproduce:
- Create a level 3 Warlock
- Give it Pact of the Blade
- Give the Warlock a 15 Charisma
- Give the Warlock a Dagger
- Edit Pact of the Blade's Effect: Enchantment and change `system.properties.foc` to `system.properties` (due to another bug with this particular class feature)
- Click on Pact of the Blade class feature to so it's ability displays in the chat area
- Drag and drop the Dagger into the chat card to apply the pact weapon effect to it
- Make an attack with the enchanted weapon
- note that the attack roll does not consider the Charisma as the ability modifier, and that it's only applying the Prof mod.

### What package are you reporting this for?

The Demon Queen Awakens

### Version

1.0.0

**Comment by maxobremer** [comment]
I think you attributed this issue/bug to the wrong content. I am assuming this is a phb issue not a demon queen awakens issue.
If so maybe close this issue and make a new issue for the right product

**Comment by maxobremer** [comment]
also for whoever is gonna fix this issue, maybe look at true strike as an example and edit as needed

**Comment by zzahringer** [comment]
> I think you attributed this issue/bug to the wrong content. I am assuming this is a phb issue not a demon queen awakens issue. If so maybe close this issue and make a new issue for the right product

Yes, I asked on Discord to have it moved to PHB, but I think the closing and redoing it is best.

Thanks, and sorry!
