### ISSUE TITLE
[Feature]: Shift town street street labels to tiles layer and place as overhead tiles 

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#73]
### What happened?

Community feedback suggests the street labels work better as tiles and I agree it's probably a better approach in this case

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.0.1

**Comment by narchymaps** [comment]
Updated tiles and foreground layer provided.
