### ISSUE TITLE
[Feature]: Give Rangers a custom Hunter's Mark spell due to Foe Slayer

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/foundryvtt-premium-content#730]
### What is the feature?

Rangers get Hunter's Mark for free which the game handles well enough. What the game doesn't handle is the increase in damage by their 20th level feature Foe Slayer. 

Duplicating Hunter's Mark to the compendium pack Character Classes and have the duplicate's damage formula use @scale.ranger.mark would resolve this

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by mattexdee** [comment]
This is "fixed" in the latest release by including a damage activity in Foe Slayer. We want to avoid creating duplicate spells because it will create issues in the Compendium Browser when picking spells. We're exploring possible options to improve this though!
