### ISSUE TITLE
[Bug]: multiclassing into a new class seems to still grant skill proficiencies 

### ISSUE THREAD

**Issue by Sillsoft42** [foundryvtt/foundryvtt-premium-content#734]
### What happened?

When you multiclass into one of the new 2024 PHB classes, the initial starting skill proficiencies of the new class still seem to get added which I don't believe should happen with the multiclassing rules.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by mattexdee** [comment]
Closing because this is fixed in the latest 1.1.2 release!
