### ISSUE TITLE
[Bug]: Sorcerer PHB Section does not include MetaMagic or Sorcerer Point details

### ISSUE THREAD

**Issue by NMyers17** [foundryvtt/foundryvtt-premium-content#740]
### What happened?

The Sorcerer Feature Table does not include the amount of Sorcerer points gained at each level, as specified in the "Level 2: Font of Magic" feature text.
![image](https://github.com/user-attachments/assets/76cdb8bc-70d2-44dd-8933-b8952e5515ca)
![image](https://github.com/user-attachments/assets/24ca9f65-3f7a-407f-87e4-170675127945)

The Sorcerer Class within the Players Handbook 2024 contains no section detailing any of the MetaMagic options available to players. These should be listed within the "Level 2: Metamagic" feature text.
![image](https://github.com/user-attachments/assets/990ff1e2-806b-47a9-a020-21732f1bb7af)
Or within a "Metamagic Options" section of the PHB within the Sorcerer class.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by krbz999** [comment]
The sorcerer points currently use the sorcerer level, but a scale value would need to be added to put them into the automatically generated sorcerer table, and then the Font of Magic feature adjusted to use that scale value instead.

**Comment by mattexdee** [comment]
Closed because it is fixed in 1.1.2 which was just released!
