### ISSUE TITLE
[Feature]: Spells granted by Feats, Pact of the Chain, Pact of the Tome, and Class levels should be selectable via dialog in advancement

### ISSUE THREAD

**Issue by w15p** [foundryvtt/foundryvtt-premium-content#752]
### What is the feature?

Spells granted by Feats, Pact of the Chain, Pact of the Tome, and Class levels should be selectable via dialog in advancement. Currently, if a Class level (or any of the other advancement features listed above) grants access to spells, those have to be manually selected and dragged onto the character sheet. Further, there is no ability to filter spells to a given Class and Subclass (though Subclass is largely handled already but see https://github.com/foundryvtt/foundryvtt-premium-content/issues/750)

I know this requires a bit of work, but the user experience of advancement would be ***greatly*** improved by its addition.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by JPMeehan** [comment]
This seems more like a feature for the core system https://github.com/foundryvtt/dnd5e/issues

**Comment by w15p** [comment]
> This seems more like a feature for the core system https://github.com/foundryvtt/dnd5e/issues

Is the subclass spell addition and Eldritch Invocation selection handled by the core system? If so, I agree but I hadn't seen and example of that outside of the content in PHB 2024

**Comment by JPMeehan** [comment]
The core system is responsible for 95% of the feature functionality — the PHB module is basically all data entry

**Comment by w15p** [comment]
https://github.com/foundryvtt/dnd5e/issues/4427
