### ISSUE TITLE
[Bug]: Core Rogue Traits table has wrong data

### ISSUE THREAD

**Issue by satz-nrw** [foundryvtt/foundryvtt-premium-content#758]
### What happened?

The Core Rogue Traits table in the PHB-Compendium has the wrong content for Skill Proficiencies. 
![image](https://github.com/user-attachments/assets/24271d25-fcd4-47a7-a1a1-086e03562e50)
It lists the effects of Level 1: Expertise but should list the different proficiencies.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.1.0

**Comment by mattexdee** [comment]
This is a system issue as the core traits tables are built automatically from the class's advancement data. I've posted an issue for it on the system for tracking: https://github.com/foundryvtt/dnd5e/issues/4453
