### ISSUE TITLE
[Bug]: Bard 1st level gives both instrument tool proficiency advancements to original class bard

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/foundryvtt-premium-content#760]
### What happened?

I believe the bottom advancement in the image below should be set to multiclass only.
![image](https://github.com/user-attachments/assets/f5a50151-0969-45c5-9efc-d192ad9a5042)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.1.2

**Comment by mattexdee** [comment]
Closing as this is resolved in the latest update.
