### ISSUE TITLE
[Bug]: Lanterns create a template, but not light from character token

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#773]
### What happened?

When a character uses a lantern (hooded or bullseye), it prompts for a measured template. Instead, it should cause the token to emit light in the specified radius/area/direction for 6 hours / charge. 
..
![image](https://github.com/user-attachments/assets/4ed1fbee-7f2c-4eb2-8991-1d6fb21e4018)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.2.0

**Comment by mattexdee** [comment]
This is not a feature that would be provided by the Player's Handbook module and would instead be handled at the system level. This request should be submitted to the [D&D5E game system](<https://github.com/foundryvtt/dnd5e/issues>) but it is likely going to be held off until there is support for active effects that impact tokens in Foundry core. As a result I'll be closing this issue.
