### ISSUE TITLE
[Bug]: Warlock attacking with Pact weapon needs Configure roll option to select damage type

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#779]
### What happened?

When the warlock attacks with its pact weapon, a dialog should pop up allowing the warlock to choose between damage types. 
![image](https://github.com/user-attachments/assets/6df27a67-908a-4cb3-94a4-6ca9a3d813ed)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.2.0

**Comment by mattexdee** [comment]
The Pact of the Blade feature includes an enchantment, that when applied to an item, will allow you to choose the type of damage when rolling and whether to use your charisma modifier or not:
<img width="415" alt="image" src="https://github.com/user-attachments/assets/79cd2afc-a8dc-4d08-afed-23376e8409ce" />
