### ISSUE TITLE
[Bug] Verify styles for the Traits class

### ISSUE THREAD

**Issue by Shandyan** [foundryvtt/foundryvtt-premium-content#78]
### What happened?

Journal entry for C21 has strange formatting around the disease (this is in the foundry programme):
![image](https://user-images.githubusercontent.com/63457907/172024545-4e760ec6-8271-485b-a777-431cbdbfb14b.png)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1.0

**Comment by silvative** [comment]
Confirmed that there seems to be a CSS issue with the traits class that is causing it to take up a lot of space. I can investigate further but there's a decent chance that @anathemamask can tell at a glance what's wrong

![image](https://user-images.githubusercontent.com/66365038/175008838-0232ba02-1057-49fd-b23d-c0702d04bc83.png)

**Comment by silvative** [comment]
Issue confirmed still present in V10

![image](https://user-images.githubusercontent.com/66365038/188276967-ca7f1785-6643-4350-8904-8dc80215abae.png)

**Comment by silvative** [comment]
Issue seems to be caused by a height: 400px in .journal-sheet.pf2e-av.compartment article.full ul

![image](https://user-images.githubusercontent.com/66365038/188277066-d685cc88-3d0c-41fe-ba2b-dbf9d82a9e87.png)
