### ISSUE TITLE
[Bug]: Polearm master needs bonus attack action for Pole Strike

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#781]
### What happened?

![image](https://github.com/user-attachments/assets/7c2b1f6c-75c8-441f-818f-1848ffa0ef99)

![Screenshot from 2024-09-28 20-42-32](https://github.com/user-attachments/assets/cc56276a-8427-4b9d-a0ef-b7494a32d0e5)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.2.0

**Comment by mattexdee** [comment]
The Polearm Master feat incudes a `Pole Strike` activity that is the bonus action attack.
