### ISSUE TITLE
[Feature]: Monsters with a recharge ability (e.g. dragon) should prompt for ability recharge on the start of their turn

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#782]
### What is the feature?

Monsters with a recharge ability (e.g. dragon) should prompt for ability recharge on the start of their turn

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by mattexdee** [comment]
This is not a feature that would be provided by the Player's Handbook module and would instead be handled at the system level. This request should be submitted to the [D&D5E game system](<https://github.com/foundryvtt/dnd5e/issues>). As a result I'll be closing this issue.

I believe this is something we're looking at including in 4.2.0 of the game system as part of the planned features for the Monster Manual 2024 though.
