### ISSUE TITLE
[Feature]: When PCs move away from a monster, prompt for reaction opportunity to GM (or player)

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#783]
### What is the feature?

When PCs move away from a monster, prompt for reaction opportunity to GM (or player)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by mattexdee** [comment]
This is not a feature that would be provided by the Player's Handbook module and would instead be handled at the system level. This request should be submitted to the [D&D5E game system](<https://github.com/foundryvtt/dnd5e/issues>). As a result I'll be closing this issue.
