### ISSUE TITLE
[Feature]: After hitting a target with guiding bolt, the next attack roll should be prompted for advantage until the end of caster's next turn

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#786]
### What is the feature?

After hitting a target with guiding bolt, the next attack roll should be prompted for advantage until the end of caster's next turn

![image](https://github.com/user-attachments/assets/a2824313-ede9-4ea1-952c-296731f7ab1e)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

**Comment by mattexdee** [comment]
This is not a feature that is currently supported by the game system but the Guiding Bolt spell does include an Active Effect that can be used for tracking when you should have advantage.
