### ISSUE TITLE
[Bug]: Entries with blank families

### ISSUE THREAD

**Issue by Zullock** [foundryvtt/foundryvtt-premium-content#793]
### What happened?

There are 96 entries that have a bunch of blank tags in the "family" category, for example: Prickly Pear Leshy, Created Fleshwarp or Draxie

![image](https://github.com/user-attachments/assets/42f1e287-938e-4ddd-92f9-0083faa8bc36)

### What package are you reporting this for?

Pathfinder Tokens: Characters

### Version

1.0.3

**Comment by silvative** [comment]
Thanks for this- I've adjusted the build process for datasheets and this theoretically will not happen any more. The script wasn't expecting the rare few entries with no family and would get confused :P
