### ISSUE TITLE
[AV] "Hunting Grounds Creatures" table can be improved with embedded actor links

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/foundryvtt-premium-content#80]
### What happened?

The roll table would be better if it included direct embedded links to the actors.

Current state:

![image](https://user-images.githubusercontent.com/6516621/172027043-8d604cac-f12a-4476-9269-aac3ed44af1a.png)

Ideal state (specific actor ID is optional):
![image](https://user-images.githubusercontent.com/6516621/172027082-ce66bede-f46c-42c3-9702-ae7235697050.png)

Comparison when rolling from the table, before & after:
![image](https://user-images.githubusercontent.com/6516621/172027102-333c7a4b-6a21-4f84-a76a-dc5461e6e7a5.png)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1.0

**Comment by silvative** [comment]
This was an intentional design choice, not an oversight- I compared both options and decided this was more readable. The actors are linked in the journal entry and duplicating the links would consititute an aesthetic downgrade with no real benefit. 

If links are preferred, they can be added.
