### ISSUE TITLE
[Bug]: The class feature Action Surge of the Fighter class is missing the Long Rest Recovery

### ISSUE THREAD

**Issue by kihayu** [foundryvtt/foundryvtt-premium-content#820]
### What happened?

# Current

The class feature _Action Surge_ states in the description

> Once you use this feature, you can't do so again until you finish a Short or Long Rest.

However in the Details tab the Recover section menu is missing the Long Rest Period.

# Should be

The class feature _Action Surge_ should recover all charges after a Long Rest.

# Reproduction

1. Install the latest version of the Player's Handbook
2. Enter a world and enable the Player's Handbook
3. Open the Character Classes Compendium
4. Open the Class Feature Fighter → Class Features → Action Surge
5. Go to tab Details
6. Recovery section at the bottom is missing the Long Rest Period

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.2.0

**Comment by mattexdee** [comment]
In the D&D5E system when a feature is set to restore on a Short Rest it will also be restored on a Long Rest so this feature works as it should. As a result I'll close this issue now.
