### ISSUE TITLE
[Bug]: Skeleton Guard tokens in Otari Graveyard are unlinked

### ISSUE THREAD

**Issue by DoggieBert** [foundryvtt/foundryvtt-premium-content#83]
### What happened?

When trying to open the pre-placed Skeleton Guard tokens in the Otari Graveyard scene the message
"This Token references an Actor which no longer exists within the World" is displayed.
![image](https://user-images.githubusercontent.com/53953028/172238711-62776e22-e1cf-4b05-aba6-3acb011185b9.png)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1.0

**Comment by esheyw** [comment]
Just wanted to pop in and say I'm still getting this on a fresh import in a fresh world: https://i.imgur.com/23oQ9Ds.png
module v1.1, foundry 9.269, pf2e 3.13.5.16

**Comment by aaclayton** [comment]
The work to fix this issue has been completed, but we are still working on milestone `1.2.0` which - once released - will contain them.
