### ISSUE TITLE
[Bug]: Broken content links in "Running Combat" chapter

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#837]
### What happened?

![image](https://github.com/user-attachments/assets/8e4ab592-d69c-4f7b-9812-04a3ee8c4ddb)

### What package are you reporting this for?

Dungeons & Dragons Dungeon Master's Guide

### Version

1.0.0

**Comment by mattexdee** [comment]
Closed as part of 1.1.0 release.
