### ISSUE TITLE
[Bug]: Encounter Maps have broken Scene Regions

### ISSUE THREAD

**Issue by alaustin0** [foundryvtt/foundryvtt-premium-content#839]
### What happened?

Scene Region Issues
- Barrow Crypt -- All regions nonfunctional (`Scene.8aWUGPa1e0XLcqq8.Region.gTP2ztfRAeoyHu9x does not exist`)
- Dragon's Lair -- All regions nonfunctional (does not exist error)
- Dungeon Hideout -- All regions lack Behaviors
- Spooky House -- Upstairs Left Main Staircase, Ground Floor Left Main Staircase, Secret Stairs, lack Behaviors. (Secret stairs may be intentional as a destination only)
- Wizards Tower -- Level 2 (Down) doesn't function when entering (no error). Level 4 (Down) teleports to itself. 

### What package are you reporting this for?

Dungeons & Dragons Dungeon Master's Guide

### Version

1.0.0

**Comment by mattexdee** [comment]
Closed as part of 1.1.0 release.
