### ISSUE TITLE
[Bug]: Missing embed in "DM's Toolbox > Hazards"

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#840]
### What happened?

![image](https://github.com/user-attachments/assets/3cb55933-cff1-4143-848d-708a13d17772)

### What package are you reporting this for?

Dungeons & Dragons Dungeon Master's Guide

### Version

1.0.0

**Comment by mattexdee** [comment]
Closed as part of 1.1.0 release.
