### ISSUE TITLE
[Bug]: 25 GP Art Objects Roll Table has an incorrect Roll Table Formula

### ISSUE THREAD

**Issue by kihayu** [foundryvtt/foundryvtt-premium-content#843]
### What happened?

# Current

The Roll Table Formula for the _25 GP Art Objects_ has the input 1d1- which looks like a typo.

# Should be

The Roll Table Formula for the _25 GP Art Objects_ should be 1d10.

# Reproduction

1. Install the latest version of the Dungeon Master's Guide
2. Enter a world and enable the Dungeon Master's Guide
3. Open the Roll Tables Compendium
4. Open the Chapter 7: Treasure → Art Objects → 25 GP Art Objects Compendium
5. See value at Roll Table Formula

### What package are you reporting this for?

Dungeons & Dragons Dungeon Master's Guide

### Version

1.0.0

**Comment by mattexdee** [comment]
Closed as part of 1.1.0 release.
