### ISSUE TITLE
[Bug]: Typo in "Running Exploration"

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#848]
### What happened?

![image](https://github.com/user-attachments/assets/02f6d1f4-c55d-4f14-8d4b-288b78224e84)

### What package are you reporting this for?

Dungeons & Dragons Dungeon Master's Guide

### Version

1.0.0

**Comment by mattexdee** [comment]
Closed as part of 1.1.0 release.
