### ISSUE TITLE
[Bug]: Brown Mold missing from hazards folder.

### ISSUE THREAD

**Issue by tslewis123** [foundryvtt/foundryvtt-premium-content#856]
### What happened?

The Brown Mold hazard is missing from the hazards folder of the equipment compendium. Because of that, the link to it in the DMG is broken.
![Untitled](https://github.com/user-attachments/assets/cf9e3c15-8b42-42d6-923e-022f1da05da1)

### What package are you reporting this for?

Dungeons & Dragons Dungeon Master's Guide

### Version

1.0.0

**Comment by mattexdee** [comment]
Closed as part of 1.1.0 release.
