### ISSUE TITLE
[Bug]: Cartographer's tools appear twice in the compendium with different configuration

### ISSUE THREAD

**Issue by johnraz** [foundryvtt/foundryvtt-premium-content#860]
### What happened?

When searching the compendium globally I find 2 Cartographer's tools item.

![image](https://github.com/user-attachments/assets/49437916-f39a-459d-b0c8-8600749b334a)

Not sure if this is an actual bug but it is at best confusing 😉 

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.2.0

**Comment by johnraz** [comment]
One of them was imported by DDBI and wrongly flagged as PHB -> IMO it shouldn't be flagged under the same "source", not sure if this can be fixed though 😉

**Comment by mattexdee** [comment]
Thanks for figuring that out @johnraz! That's something that will have to be handled on their end as they're configuring the source during import and we can't control that aspect so I'll close this issue on our end.
