### ISSUE TITLE
[Bug]: Beluthus actor's size category reverts to Large despite the presence of an actor override

### ISSUE THREAD

**Issue by goodkinghadrian** [foundryvtt/foundryvtt-premium-content#89]
### What happened?

Beluthus in area I29 should be small-sized, but his actor sheet and token have him as large.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1.0

**Comment by silvative** [comment]
The base Devourer creature is Large and Beluthus is a unique one with an override to his size category. Changes have been made to #build-world branch to reflect him being Small. @aaclayton Will we need an exception in the importer to prevent them from being overwritten with the size of the system compendium actor?

**Comment by aaclayton** [comment]
Yes, we will need to apply an import override to preserve the override to this actor's size category.

**Comment by silvative** [comment]
I give up on this one. I've gone as far as deleting the actor and recreating a new one with a different ID and I can't get the size override to stick- is size not included in the data ?
