### ISSUE TITLE
[Bug]: "Send to chat" button on @check inline prompts is missing

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#90]
### What happened?

Appearance of the print-to-chat button on @check inline links appears to have gained a border  since we last worked on the CSS for them. Not sure if we want to change it back, it doesn't actually look too bad? It may have been an intentional one that I just missed you making.

![image](https://user-images.githubusercontent.com/66365038/175006193-8706f119-6a5b-42ab-a260-bbaaa172ac44.png)

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1.0

**Comment by stwlam** [comment]
This is a system change. I would have figured the module had in place a CSS reset, but all's well that ends well?

**Comment by silvative** [comment]
An update, the "send to chat" icon is fully missing in V10, but it may also be due to a system change. 
- Should we be considering a CSS reset to avoid system changes? 
- Can we restore the "send to chat" button?

![image](https://user-images.githubusercontent.com/66365038/188277175-981f7268-b549-4ca7-b116-f384c2fe33a9.png)

**Comment by silvative** [comment]
Potentially system issue, posted here https://github.com/foundryvtt/pf2e/issues/3782
