### ISSUE TITLE
[Bug]: Compendium Image Assignment is non-functional on V10 branch

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt-premium-content#93]
### What happened?

The same issue is present in the AV module. To reproduce:

1. Open a compendium with actor and token art replaced.
2. Open a modified NPC directly from the compendium.

![image](https://user-images.githubusercontent.com/106829671/175619042-43b9abce-70c5-4379-8ee6-376177874aeb.png)

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

1.1.0

**Comment by silvative** [comment]
Compendium image mapping confirmed non-functional in the V10 development branch- perhaps we could solve both the original issue and this new, more serious one by adopting the system's image mapping feature.

**Comment by silvative** [comment]
Resolved by leveraging the system-provided featureset and the inclusion of an image mapping file 
![image](https://user-images.githubusercontent.com/66365038/187303309-89720ec2-dd57-4aa3-bb7a-c303a9f4945e.png)
