### ISSUE TITLE
[Bug] Azvaligander token missing 1.5 scaling

### ISSUE THREAD

**Issue by Dorako** [foundryvtt/foundryvtt-premium-content#97]
### What happened?

![image](https://user-images.githubusercontent.com/1561190/178113330-dd74463d-8742-4618-ba03-3402cc97bc58.png)
Azvaligander is a small creature using a 'breakthrough' token requiring an 1.5 scaling to render him the expected size (see creature on the left)

Somewhat related, Blood of Belcorra on floor 1 is also rendered smaller than expected, but perhaps this is an artistic choice - her size scaling is set to unlinked, yet the multiplier is 1.0. 1.5 would make her 'normal' sized.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1

**Comment by silvative** [comment]
Changed on world branch, but will need an import update similar to https://github.com/foundryvtt/foundryvtt-premium-content/issues/89

**Comment by silvative** [comment]
"uyGxJOnJ1gYwOpy5": {
      "actor": "modules/pf2e-abomination-vaults/assets/bestiary-portraits/ch-07/azvalvigander.webp",
      "token": {
        "img": "modules/pf2e-abomination-vaults/assets/bestiary-tokens/ch-07/azvalvigander.webp",
        "scale": 1.5
      }


Image mapping seems to set it correctly, it's possible we're overwriting this in our import script.
